
라이언 홀리데이가 쓴 @holiday2017dailystoicjournal 의 내용을 기계 번역한 것입니다.

# 서문

먼 게르마니아 땅, 그라누아 강변의 최전선 텐트에서 마르쿠스 아우렐리우스 황제는 새벽을 맞이했습니다. 이른 기상이 힘겨웠지만, 그것이 자신의 소명임을 되새기며 기꺼이 몸을 일으켰습니다. 등불 아래 책상에 앉아, 앞으로 마주할 일들을 떠올리며 그리스어로 일기를 쓰기 시작했습니다. 

"오늘 나는 참견하기 좋아하는 사람, 은혜를 모르는 사람, 자기중심적인 사람, 거짓말쟁이, 질투하는 사람, 괴짜를 만날 것이다." 

그는 황제로서 군대를 이끌고 제국을 통치하며 겪어야 할 피할 수 없는 어려움에 대비해, 스스로 이렇게 쓰며 마음을 다잡았습니다.

하지만 이것은 불평이 아니었습니다. 그의 어조에서 좌절이나 분노의 기색은 찾아볼 수 없었습니다.

마르쿠스 아우렐리우스는 자신이 사랑하고 의지하는 스토아 철학을 삶에서 실천하고 있었습니다. 그는 동료와 신하들을 무시하지 않았습니다. 오히려 생각을 정리하며 참견쟁이와 배은망덕한 사람들에 대해 이렇게 말했을 것입니다. 

"아무도 나에게 해를 끼치거나 추함에 물들게 할 수 없다. 나는 내 동족에게 화를 내거나 미워할 수 없다. 우리는 서로 협력하도록 태어났기 때문이다." 

그는 아침 일기를 계속 써 내려갔습니다. 어떻게 생각하고 어떻게 살아야 하는지, 그리고 무엇에 감사해야 하는지에 대한 짧은 메모를 남겼습니다. 그리고 단순히 철학자가 아닌, 진정한 '철학자 왕'으로서 하루를 맞이하러 나아갔습니다.

시간을 조금 더 거슬러 올라가 보겠습니다. 마르쿠스의 아침 명상보다 약 1세기 전, 어느 날 저녁에 또 다른 스토아 철학자 역시 아주 비슷한 일을 하고 있었습니다. 그의 이름은 세네카였습니다. 그는 권력자이자 극작가였고, 네로 황제의 궁정에서 최고위층에 있던 대중 지식인이었습니다. 그는 아침 대신 밤에 일기 쓰는 것을 선호하며 매일 자신을 성찰했습니다. 세네카는 저문 하루를 돌아보며 자신의 행동이 올바랐는지, 무엇을 더 잘할 수 있었는지, 어떤 습관을 고쳐야 하는지, 그리고 어떻게 자신을 향상시킬 수 있는지 자문하곤 했습니다. 그는 이 밤의 일과에 대해 형에게 이렇게 말했습니다.
"우리는 앞으로 할 일을 계획하지만, 미래를 위한 계획은 과거로부터 비롯된다."

전날을 복기하는 일은 세네카가 다음 날 아침을 준비하는 데 큰 도움이 되었습니다.

또 다른 유명한 스토아 철학자 에픽테토스는 세네카나 마르쿠스처럼 편안하고 강력한 삶을 살지 못한 전직 노예였습니다. 그는 학생들에게 교훈을 복습하고 기록하라고 끊임없이 상기시켰습니다. 《담화록》에서 그는 "밤낮으로 이런 생각들을 가까이에 두고, 그것들을 쓰고 소리 내어 읽으며 자신과 다른 사람들에게 이야기하라"고 말합니다.

이처럼 아침의 준비와 저녁의 복기는 스토아 철학에서 가장 중요하고 서로 연결된 두 가지 수련이며, 2천 년이 넘는 전통입니다. 《데일리 스토익 저널》을 손에 든 당신은 이제 그 전통의 계승자입니다. 좋은 삶을 추구하며 하루에 두 번 이 수련을 이어갈 수 있습니다.

다른 많은 철학과 달리 스토아 철학은 단순히 우주를 설명하기 위해 만들어지지 않았습니다. 우리가 어디에서 왔는지에 대한 복잡한 질문이나 이론적인 논의에 크게 관심을 두지 않았습니다. 스토아 철학은 그리스인이 창시하고 로마인이 완성했으며, 혼란스러운 세상에서 살아가려는 사람들을 위한 일상생활의 지침이었습니다. 따라서 그것은 일련의 가르침이나 오래된 문장들 이상이었습니다. 그것은 두려움을 줄이는 시스템이었고, 파괴적인 생각을 물리치는 사고방식이었으며, 우리가 당연하게 여기는 것들을 일깨워주는 알림이었고, 유혹에 저항하는 도구였으며, 힘든 순간을 위한 버팀목과 같은, 시대를 초월한 실용적인 수련들의 집합이었습니다. 이는 스토아 철학이 한 번 배우거나 읽고 마는 것이 아니라, 지속적으로 연구하고 실천해야 함을 의미합니다.

마르쿠스 아우렐리우스의 유일한 저작인 《명상록》의 제목을 생각해 보십시오. 그는 노년에도 여전히 배우고 실천하는 철학적 원리에 대해 자신을 위해 '명상'하고 있었습니다. 세네카의 편지를 들여다봐도 같은 것을 발견할 수 있습니다. 그는 타인에게 편지를 쓰고 있지만, 의도된 청중은 분명 자기 자신입니다. 그는 소리 내어 생각하고 있습니다. 에픽테토스 역시 제자 아리아노스가 쓴 노트 형태로 살아남았는데, 마치 그의 하루가 학생들의 끝없는 질문에 답하며 보낸 것처럼 읽힙니다. "이것에 대해 어떻게 해야 합니까?", "저런 것을 어떻게 다룰 수 있습니까?", "제가 ____할 때 조언이 있습니까?"

우리의 책 《데일리 스토익》에서 우리는 이 지혜의 모음을 바쁜 독자들이 소화하고 접근하기 쉬운 방식으로 제공하고자 했습니다. 스토아 학파 원전을 번역하고 재출판하는 대신(이것은 이미 여러 번 아주 잘 이루어졌습니다), 우리는 모든 위대한 스토아 학파의 최초 단권 모음집을 만들고 매일 한 명의 생각을 강조하도록 배열했습니다. 그 책에 대한 반응은 놀라웠습니다. 전국 베스트셀러 목록에 3개월 동안 머물렀고, 아마 2천 년 만에 가장 큰 단일 스토아 학파 모임이었던 기조 연설의 형태로 데뷔했습니다. DailyStoic.com의 뉴스레터는 구독자로 넘쳐났고, 이는 매일 아침 수만 명의 야망 있는 스토아 학파가 모두 같은 것을 동시에 읽고 있다는 것을 의미했습니다. 우리는 또한 매일의 명상에서 영감을 받은 생각으로 《데일리 스토익》과 몰스킨 저널의 페이지를 가득 채운 독자들의 인증 사진을 보기 시작했습니다.

이에 대한 응답으로 우리는 이 저널, 즉 《데일리 스토익》의 동반자 안내서이자 철학을 실천하려는 모든 사람을 위한 자료를 만들기로 했습니다. 이제 여러분이 그것을 손에 들고 있다는 것을 영광으로 생각합니다.

### 이 저널을 사용하는 방법

이 책은 일 년 52주에 맞춰, 매주 하나의 스토아적 규율이나 실천을 제시합니다. 각 실천은 그 중요성과 적용에 대한 약간의 지침과 함께 제시되며, 한 주 동안 주의를 집중하는 데 도움이 되는 위대한 스토아 철학자들의 인용문이 함께 제공됩니다. 각 주별 실천에 대한 첫 번째 인용문은 《데일리 스토익》의 같은 주에서 직접 가져온 것입니다. 매일 아침의 준비나 저녁의 성찰(혹은 둘 다)에 집중할 수 있도록 돕는 질문을 던집니다. 이 질문들은 여러분이 《데일리 스토익》을 따라 읽든, 우리의 일일 뉴스레터를 읽든, 또는 다른 어떤 자료를 사용하든 효과가 있을 것입니다.

우리는 맹목적으로 따라야 하는 계명이나 단계별 시스템을 만들지 않았습니다(프롬프트에 응답하고 싶지 않다면 무시하고 가장 유익하다고 생각하는 것에 대해 쓰십시오. 뒤쪽에 다른 참고 자료도 남겨두었습니다). 세네카가 말했듯이 "이 길을 개척한 사람들은 우리의 주인이 아니라 우리의 안내자입니다. 진실은 모든 사람에게 열려 있습니다. 아직 독점되지 않았습니다."
이러한 스토아적 실천이 그토록 오래 지속되고 현대에 부활을 누리는 이유는 그것들이 우리가 일상적으로 직면하는 상황, 즉 리처드 소랍지가 "삶의 평범한 우여곡절, 사별, 실직, 승진, 치열한 경쟁, 돈, 침략, 도시 약탈, 추방, 건강에 대한 걱정"이라고 부르는 것에 끊임없이 초점을 맞추고 있기 때문입니다. 미국 철학자 브랜드 블랜샤드가 마르쿠스 아우렐리우스의 유산에 대해 감탄했듯이:

"이제 로마 지휘관들의 행군과 역행군에 관심을 갖는 사람은 거의 없습니다. 수 세기 동안 사람들을 사로잡은 것은 실제 삶이 거의 알려지지 않은 한 남자의 생각 노트입니다. 그는 한밤중의 어둠 속에서 그날의 사건이나 내일의 계획이 아니라 훨씬 더 영구적인 관심사, 즉 희귀한 영혼이 살았던 이상과 열망을 적었습니다."

로마 스토아 학파는 말이 아니라 행동에 초점을 맞췄습니다. 세네카가 기억에 남게 말했듯이 "철학은 말하는 법이 아니라 행동하는 법을 가르칩니다." 일상적으로 우리의 행동을 개선하려는 이러한 노력은 에픽테토스가 그의 가르침의 중심에 두었던 것으로, 그의 경고 "단순한 학습에 만족하지 말고 실천을 더한 다음 훈련을 더하라"에 요약되어 있습니다.

이 저널은 진보(prokope)의 길에서 배우는 것을 기억하고 적용하려고 노력할 때 주의(prosoche)와 실천(melete)에 집중할 수 있는 곳입니다. 이 저널에 제시된 스토아적 규율을 추구할 때, 매일 아침 위대한 현대 스토아 철학자 피에르 아도가 말했듯이 "어떤 원칙이 내 행동을 인도하고 영감을 줄 것인가?"라고 자문하게 될 것입니다. 그리고 매일 저녁 여러분은 그 원칙에 미치지 못한 부분과 진전을 이룬 부분을 검토하게 될 것입니다. 여러분은 원하는 날짜에 시작하여 책이 완성될 때까지 진행할 수 있습니다.

함께하는 52개의 이상과 열망은 모든 상황에 대해 무언가를 제공합니다. 불평(31주), 미루기(35주) 또는 공황(39주)과 같은 나쁜 습관을 다루든, 분노(29주), 미래에 대한 두려움(34주) 또는 싫어하는 사람들을 다루는 것(38주)에 대한 덜 파괴적인 대안을 찾든, 여러분은 사용할 실용적인 도구를 찾을 수 있을 것입니다. 여러분은 "위에서 본 관점"(22주)을 취하는 수련을 배우거나, 다른 사람들이 보는 것처럼 사물을 보는 법(11주)을 배우고, 롤모델(23주)을 정함으로써 강력한 관점을 얻게 될 것입니다. 여러분은 통제의 이분법(1주), 현재 순간에 집중하기(5주) 또는 인상을 시험하는 방법(15주)과 같은 스토아 철학의 기본을 스스로 훈련하게 될 것입니다.

이것이 완벽한 현자처럼 살 수 있는지, 또는 당신보다 길을 더 멀리 간 사람의 교정을 피할 수 있는지 확인하는 대회가 아니라는 것을 기억하는 것이 중요합니다. 철학을 그런 식으로 사용하는 사람은 단호하게 비스토아적입니다! 세네카가 우리에게 상기시켰듯이 "철학이 다른 사람의 결점을 비난하는 수단이 되기보다는, 자신의 결점을 긁어내게 하십시오."

이 저널을 매일 아침과 저녁에 양치질하는 것처럼, 자신의 영혼을 위한 솔이라고 생각하십시오.

이 책의 마지막에 있는 마지막 교훈은 스토아 철학의 가장 본질적인 교훈입니다. 말을 행동으로 바꾸는 법을 배우는 것입니다. 우리는 여러분이 그곳까지 도달하기를 바라며, 만약 그렇게 한다면 다음 해에 다시 같은 여정을 시작하도록 격려합니다. 왜냐하면 여러분은 헤라클레이토스가 말했듯이 더 이상 같은 사람이 아닐 것이고, 이것도 같은 책이 아닐 것이기 때문입니다.

# 1주차: 우리에게 달려 있는 것 우리에게 달려 있지 않은 것

에픽테토스의 핸드북(엔키리디온)은 모든 스토아 철학에서 가장 강력한 수련으로 시작합니다. 즉 "우리에게 달려 있는 것"(우리의 통제하에 있는 것)과 "우리에게 달려 있지 않은 것"을 구별하는 것입니다. 이것이 바로 통제의 이분법이며 전체 철학의 첫 번째 원리입니다. 우리는 삶에서 추구하는 많은 것들을 통제하지 못하지만 그것들을 얻지 못했을 때 화를 내고 슬퍼하고 상처받고 두려워하거나 질투하게 됩니다. 사실 그러한 감정 즉 그러한 반응들이 우리가 통제하는 유일한 것입니다. 그것이 여러분이 올해에 대해 일기를 쓰거나 기억하는 유일한 교훈이라면 그것을 잘 그리고 철학적으로 산 한 해로 여기십시오.

> "인생의 주요 과제는 간단히 이것입니다. 문제를 식별하고 분리하여 '내 통제하에 있지 않은 외부적인 것'과 '내가 실제로 통제하는 선택과 관련된 것'을 명확하게 스스로에게 말할 수 있도록 하는 것입니다. 그렇다면 나는 선과 악을 어디에서 찾아야 할까요? 통제할 수 없는 외부적인 것이 아니라 내 자신의 선택인 내 안에서 찾아야 합니다..."
> —에픽테토스, 《담화록》, 2.5.4-5

> "어떤 것은 우리의 통제하에 있고 다른 것은 그렇지 않습니다. 우리는 우리의 의견, 선택, 욕망, 혐오, 한마디로 우리 자신의 모든 행동을 통제합니다. 우리는 우리의 몸, 재산, 명성, 지위, 한마디로 우리 자신의 행동이 아닌 모든 것을 통제하지 않습니다. 더욱이 우리의 통제하에 있는 것들은 본질적으로 자유롭고 방해받지 않으며 장애물이 없지만 우리의 통제하에 있지 않은 것들은 약하고 노예 같고 방해받을 수 있으며 우리 자신의 것이 아닙니다."
> — 에픽테토스, 《엔키리디온》, 1.1-2

> "우리는 우리의 이성적인 선택과 그 도덕적 의지에 의존하는 모든 행동을 통제합니다. 우리의 통제하에 있지 않은 것은 신체와 그 일부, 우리의 소유물, 부모, 형제자매, 자녀 또는 국가, 즉 우리가 연관될 수 있는 모든 것입니다."
> —에픽테토스, 《담화록》, 1.22.10

::: {.callout-note title="1월 1일: 진정으로 내 통제하에 있는 것은 무엇인가?" icon="false"}
<br/>
<br/>
<br/>
:::

::: {.callout-note title="1월 2일: 나는 무엇을 배우고 공부하고 있는가?" icon="false"}
<br/>
<br/>
<br/>
:::

::: {.callout-note title="1월 3일: 중요한 것에 '예'라고 말하기 위해 '아니오'라고 말할 수 있는 것은 무엇인가?" icon="false"}
<br/>
<br/>
<br/>
:::

::: {.callout-note title="1월 4일: 나는 명확하게 보고 있는가? 관대하게 행동하고 있는가? 바꿀 수 없는 것을 받아들이고 있는가?" icon="false"}
<br/>
<br/>
<br/>
:::

::: {.callout-note title="1월 5일: 내 삶의 목적은 무엇인가?" icon="false"}
<br/>
<br/>
<br/>
:::

::: {.callout-note title="1월 6일: 나는 누구이며 무엇을 상징하는가?" icon="false"}
<br/>
<br/>
<br/>
:::

::: {.callout-note title="1월 7일: 어떻게 하면 내 마음을 오염으로부터 맑게 유지할 수 있을까?" icon="false"}
<br/>
<br/>
<br/>
:::

# 2주차: 선택의 영역

첫 번째 단계가 우리의 통제하에 있는 것과 그렇지 않은 것을 분별하는 것이라면 두 번째 단계는 우리가 선택할 수 있는 것에 에너지를 집중하는 것입니다. 스토아 학파는 영혼을 잘 조율되고 잘 인도될 때 어떤 시련이나 상황에도 무적의 요새가 되는 구체로 보았습니다. 우리의 이성에 의해 보호되는 이 선택의 영역(prohairesis)은 신성한 사원과 같으며 우리가 삶에서 진정으로 소유하는 유일한 것입니다. 우리는 우리의 선택의 산물이므로 우리가 잘 선택하는 것이 필수적입니다. 이번 주에는 감정 행동 신념 우선순위에 대한 선택에 대해 생각하고 성찰하십시오.

> "새벽에, 그리고 낮과 밤 내내 이 생각을 준비해 두십시오. 행복으로 가는 길은 단 하나뿐이며 그것은 당신의 선택 영역 밖의 모든 것을 포기하고 다른 어떤 것도 당신의 소유물로 여기지 않고 다른 모든 것을 신과 행운에 맡기는 것입니다."
> —에픽테토스, 《담화록》, 4.4.39

> "그렇다면 누가 무적인가? 이성적인 선택 밖의 어떤 것에도 화를 내지 않는 사람이다."
> —에픽테토스, 《담화록》, 1.18.21

> "영혼은 구체이며 그 자체에 충실하다. 그것은 어떤 외부적인 것으로 자신을 투사하지도 않고 자신에게 붕괴되지도 않으며 대신 모든 것의 진실과 그 자체의 진실을 보여주는 빛을 발산한다."
> —마르쿠스 아우렐리우스, 《명상록》, 11.12

::: {.callout-note title="1월 8일: 나는 무엇에 중독되어 있는가?" icon="false"}
<br/>
<br/>
<br/>
:::

::: {.callout-note title="1월 9일: 나에게 일어나는 일을 통제할 수 없다면 무엇이 남는가?" icon="false"}
<br/>
<br/>
<br/>
:::

::: {.callout-note title="1월 10일: 어디에서 안정감을 찾을 수 있을까?" icon="false"}
<br/>
<br/>
<br/>
:::

::: {.callout-note title="1월 11일: 내 삶의 불안정성의 원천은 무엇인가?" icon="false"}
<br/>
<br/>
<br/>
:::

::: {.callout-note title="1월 12일: 평온으로 가는 길은 어디에 있는가?" icon="false"}
<br/>
<br/>
<br/>
:::

::: {.callout-note title="1월 13일: 내 통제권 밖으로 무엇을 둘 수 있을까?" icon="false"}
<br/>
<br/>
<br/>
:::

::: {.callout-note title="1월 14일: 무엇이 나를 괴롭히는가?" icon="false"}
<br/>
<br/>
<br/>
:::

# 3주차: 깨어나기

매일 이 일지에 글을 쓸 때마다 여러분은 에픽테토스 마르쿠스 아우렐리우스 그리고 다른 모든 위대한 스토아 철학자들의 발자취를 따르게 될 것입니다. 스토아 철학자들은 변덕스럽게 하루를 맞이하지 않고 준비와 훈련으로 하루를 맞이했습니다. 그들은 하루 한 주 일 년 동안 다가올 일에 대해 생각하고 예상하는 데 실제 시간을 보냈습니다. 일기 쓰기를 포함한 매일 아침 활동은 그들이 하루를 맞이할 준비를 하도록 고안되었습니다. 그리고 이 책에서의 여러분의 작업으로 여러분도 그렇게 될 것입니다.

> "그렇다면 당신 자신은 어떻습니까? 당신은 매일 자신에게 '나는 오늘 무엇을 했는가?'라고 묻습니까? 당신은 '나는 어떤 실수를 저질렀는가?', '나는 무엇을 더 잘할 수 있었는가?', '나는 어떤 습관을 고쳐야 하는가?'라고 묻습니까? 이것이 우리 자신의 행동을 점검하는 방법입니다."
> — 에픽테토스, 《담화록》, 4.6.34-35 (의역)

> "아침에 일어나기 힘들 때 이 생각을 명심하십시오. 나는 인간의 일에 깨어나고 있다. 그렇다면 내가 만들어진 목적 바로 이 세상에 태어난 이유인 일을 하러 가는 것에 왜 짜증을 내는가? 아니면 나는 이불 밑에 웅크리고 따뜻하게 지내기 위해 만들어졌는가? 그것은 매우 즐겁다. 그렇다면 당신은 쾌락을 위해 만들어졌는가? 요컨대 응석받이로 자라기 위해서인가 아니면 자신을 단련하기 위해서인가?"
> —마르쿠스 아우렐리우스, 《명상록》, 5.1
::: {.callout-note title="1월 15일: 나는 항로를 유지하고 있는가 아니면 벗어나고 있는가?" icon="false"}
<br/>
<br/>
<br/>
:::

::: {.callout-note title="1월 16일: 나는 어떤 가정을 의심 없이 받아들였는가?" icon="false"}
<br/>
<br/>
<br/>
:::

::: {.callout-note title="1월 17일: 나는 의미 있는 일을 하고 있는가?" icon="false"}
<br/>
<br/>
<br/>
:::

::: {.callout-note title="1월 18일: 다른 사람들이 간과하는 곳에서 우아함과 조화를 찾을 수 있을까?" icon="false"}
<br/>
<br/>
<br/>
:::

::: {.callout-note title="1월 19일: 좋든 나쁘든 높든 낮든 나는 여전히 선택권이 있는가?" icon="false"}
<br/>
<br/>
<br/>
:::

::: {.callout-note title="1월 20일: 어떻게 하면 내 원칙을 다시 불태우고 오늘부터 살기 시작할 수 있을까?" icon="false"}
<br/>
<br/>
<br/>
:::

::: {.callout-note title="1월 21일: 나는 일기 쓰기 의식에서 무엇을 얻고 있는가?" icon="false"}
<br/>
<br/>
<br/>
:::

# 4주차: 매일 조금씩 더 나아지기

스토아 학파는 자신의 삶을 진행 중인 작업으로 보았습니다. 그들은 자신이 완벽하게 태어났다고 믿지 않았지만 노력과 헌신으로 매일 조금씩 더 나아질 수 있다고 믿었습니다. 에픽테토스가 소크라테스의 말을 인용했듯이 이러한 진보에는 진정한 기쁨이 있습니다. 마르쿠스 아우렐리우스는 책 멘토 역사적 사례에서 조언을 열심히 찾으며 자신의 교육과 개선을 열렬히 추구했습니다. 이번 주에는 그 예를 따르고 매일이 지날수록 조금씩 더 나아지는 자신을 확인하십시오.

세네카가 표현했듯이 우리는 끊임없이 자신을 감시하고 매일매일을 검토해야 합니다. 하루를 되돌아보는 것은 우리가 부족했을 수 있는 부분을 더 잘 이해하는 데 도움이 되며 개선하고 성장하는 방법에 대한 구체적인 피드백을 제공합니다. 측정하고 기록하는 것만이 모니터링될 수 있으며 반성하는 것만이 배울 수 있습니다.

> "우리는 서로를 돕기 위해 태어났습니다. 당신이 누군가를 도울 수 있다면 그것은 당신의 의무입니다."
> —세네카, 《도덕 서한》, 95.52 (의역)

> "루스티쿠스로부터... 나는 주의 깊게 읽고 전체에 대한 대략적인 이해에 만족하지 않으며 어떤 것에 대해 할 말이 많은 사람들에게 너무 빨리 동의하지 않는 법을 배웠다."
>
> -마르쿠스 아우렐리우스, 《명상록》, 1.7.3

> "그러나 소크라테스는 무엇이라고 말하는가? '한 사람이 자신의 농장을 개선하는 것을 기뻐하고 다른 사람이 자신의 말을 기뻐하는 것처럼 나는 매일 내 자신의 개선에 힘쓰는 것을 기뻐한다.'"
>
> -에픽테토스, 《담화록》, 3.5.14

::: {.callout-note title="1월 22일: 오늘 나는 어떤 나쁜 습관을 고쳤는가?" icon="false"}
<br/>
<br/>
<br/>
:::

::: {.callout-note title="1월 23일: 내 소유물 중 어느 것이 나를 소유하고 있는가?" icon="false"}
<br/>
<br/>
<br/>
:::

::: {.callout-note title="1월 24일: 나는 깊이 있는 일을 하고 있는가?" icon="false"}
<br/>
<br/>
<br/>
:::

::: {.callout-note title="1월 25일: 나는 진정으로 무엇을 소중히 여기는가?" icon="false"}
<br/>
<br/>
<br/>
:::

::: {.callout-note title="1월 26일: 오늘의 내 만트라는 무엇인가?" icon="false"}
<br/>
<br/>
<br/>
:::

::: {.callout-note title="1월 27일: 나는 무엇을 공부하고 연습하고 훈련하고 있는가?" icon="false"}
<br/>
<br/>
<br/>
:::

::: {.callout-note title="1월 28일: 나는 어떤 잣대로 나 자신을 측정하는가?" icon="false"}
<br/>
<br/>
<br/>
:::

# 5주차: 현재 순간에 집중하기

마르쿠스 아우렐리우스는 특히 격동의 시기에 통치했습니다. 여러 전선에서 전쟁이 발발했고 끔찍한 전염병이 로마를 휩쓸었습니다. 그의 통치는 확실히 끊임없는 압박의 연속이었습니다. 그러나 그는 결코 그것에 압도당하지 않았습니다. 스토아 학파와 그의 양아버지인 안토니누스 피우스 황제의 예에서 마르쿠스는 항상 현재 순간과 당면한 의무에 충실함으로써 대처 전략을 찾았습니다. 우리 자신의 스트레스가 끓어오를 때 우리는 그의 실천과 수련을 기억하여 우리 앞에 있는 것에 충실하고 그것이 의미할 수 있는 모든 것에 충실하지 않을 수 있습니다.

> "매 순간 로마인이자 인간으로서 당면한 과제에 굳건한 마음을 유지하고 엄격하고 단순한 존엄성 애정 자유 정의로 그것을 행하며 다른 모든 고려 사항으로부터 자신에게 휴식을 주십시오. 각 과제를 마지막인 것처럼 접근하고 모든 산만함 이성의 감정적 전복 모든 드라마 허영심 공정한 몫에 대한 불평을 포기하면 이것을 할 수 있습니다. 몇 가지에 대한 숙달이 풍요롭고 경건한 삶을 사는 것을 어떻게 가능하게 하는지 볼 수 있습니다."
>
> -마르쿠스 아우렐리우스, 《명상록》, 2.5

> "도움을 요청하는 것을 부끄러워하지 마십시오. 당신은 성벽을 공격하는 군인과 같습니다. 만약 당신이 부상을 입어 다른 사람의 도움 없이는 성벽을 오를 수 없다면 어떻게 하겠습니까?"
> —마르쿠스 아우렐리우스, 《명상록》, 7.714

> "인생 전체에 대한 성찰이 당신을 짓누르게 하지 마십시오. 아직 일어날 수 있는 모든 나쁜 일들로 마음을 채우지 마십시오. 현재 상황에 집중하고 왜 그것이 그렇게 견딜 수 없고 살아남을 수 없는지 자문해 보십시오."
> —마르쿠스 아우렐리우스, 《명상록》, 8.36
::: {.callout-note title="1월 29일: 나는 당면한 과제에 굳건한 마음을 유지하고 있는가?" icon="false"}
<br/>
<br/>
<br/>
:::

::: {.callout-note title="1월 30일: 중요하지 않은 일에 대해 무지한 것에 만족하는가?" icon="false"}
<br/>
<br/>
<br/>
:::

::: {.callout-note title="1월 31일: 오늘 철학이 나를 치유하는 데 어떤 도움을 줄 수 있을까?" icon="false"}
<br/>
<br/>
<br/>
:::

::: {.callout-note title="2월 1일: 어떻게 하면 내 성질을 이겨낼 수 있을까?" icon="false"}
<br/>
<br/>
<br/>
:::

::: {.callout-note title="2월 2일: 어떤 충동이 나의 자제력을 앗아가는가?" icon="false"}
<br/>
<br/>
<br/>
:::

::: {.callout-note title="2월 3일: 내가 통제하고 있는가 아니면 내 불안이 통제하고 있는가?" icon="false"}
<br/>
<br/>
<br/>
:::

::: {.callout-note title="2월 4일: 나는 선택할 수 있는 나의 힘의 무적성을 기르고 있는가?" icon="false"}
<br/>
<br/>
<br/>
:::

# 6주차: 의견을 보류하라

에픽테토스는 의견이 "혼란스러운 마음의 원인"이라고 가르쳤습니다. 우리가 생각하는 방식, 되어야 할 방식에 대한 의견입니다. "의견"에 대한 스토아 학파의 단어 중 하나는 "독단"입니다. 스토아 철학의 실천은 이러한 독단적인 삶의 방식을 중단하려는 끊임없는 시도 즉 자신의 의견과 기대를 세상에 강요할 수 있다는 믿음의 중단으로 시작됩니다.

> "우리는 어떤 것에 대해 의견을 갖지 않고 그것이 우리의 마음 상태를 화나게 하지 않도록 할 힘이 있습니다. 왜냐하면 사물은 우리의 판단을 형성할 자연적인 힘이 없기 때문입니다."
>
> -마르쿠스 아우렐리우스, 《명상록》, 6.52

> "당신의 영혼은 당신의 매일의 생각에 의해 물들여집니다."
> —마르쿠스 아우렐리우스, 《명상록》, 5.16 (의역)

> "인간에게서 뿌리 뽑아야 할 두 가지가 있는데 그것은 오만한 의견과 불신이다. 오만한 의견은 더 이상 필요한 것이 없다고 기대하고 불신은 상황의 급류 속에서 행복이 있을 수 없다고 가정한다."
>
> -에픽테토스, 《담화록》, 3.14.8

> "당신의 성격은 당신의 선택의 결과입니다."
> —에픽테토스, 《담화록》, 1.18.21 (의역)
::: {.callout-note title="2월 5일: 나는 행동하기 전에 생각하고 있는가?" icon="false"}
<br/>
<br/>
<br/>
:::

::: {.callout-note title="2월 6일: 어떤 불필요한 갈등을 피할 수 있을까?" icon="false"}
<br/>
<br/>
<br/>
:::

::: {.callout-note title="2월 7일: 두려움과 걱정이 나를 정복하기 전에 어떻게 그것들을 정복할 수 있을까?" icon="false"}
<br/>
<br/>
<br/>
:::

::: {.callout-note title="2월 8일: 나의 분노가 상황을 더 좋게 만든 적이 있는가?" icon="false"}
<br/>
<br/>
<br/>
:::

::: {.callout-note title="2월 9일: 이것에 대해 의견이 없었다면 어땠을까?" icon="false"}
<br/>
<br/>
<br/>
:::

::: {.callout-note title="2월 10일: 내 삶의 어떤 부분이 분노에 의해 움직이는가?" icon="false"}
<br/>
<br/>
<br/>
:::

::: {.callout-note title="2월 11일: 내 영혼은 좋은 통치자인가 아니면 폭군인가?" icon="false"}
<br/>
<br/>
<br/>
:::

# 7주차: 인식을 지켜보라

매 순간 우리 주변 세계의 인상이 홍수처럼 밀려옵니다. 그리고 우리 마음은 그와 함께 일어나는 인식으로 가득 차 있습니다. 스토아 학파는 우리가 마치 매우 중요한 것을 보호하기 위해 경비를 서 있는 것처럼 이 홍수를 끊임없이 감시해야 한다고 가르칩니다. 우리가 보호하고 있는 것은 무엇일까요? 우리의 마음의 평화, 명료함, 그리고 자유, 이 모든 것은 우리의 인식에 기반을 두고 있습니다. 에픽테토스는 우리에게 중요한 것에 주의를 기울이고 우리에게 오는 끊임없는 도발 중 많은 것을 무시하는 법을 배워야 한다고 상기시킵니다.

> "당신의 인식을 끊임없이 감시하십시오. 왜냐하면 당신이 보호하고 있는 것은 작은 것이 아니라 당신의 존중 신뢰성 안정성 마음의 평화 고통과 두려움으로부터의 자유 한마디로 당신의 자유이기 때문입니다. 이 모든 것을 무엇과 바꾸시겠습니까?"
>
> -에픽테토스, 《담화록》, 4.3.6B-8

> "철학에서 시작하기에 중요한 곳은 이것입니다. 즉 자신의 지배 원리에 대한 명확한 인식입니다."
>
> -- 에픽테토스, 《담화록》, 1.26.15

> "나는 홍수 한가운데로 무모하게 뛰어들어 격동의 삶을 받아들이고 어려운 상황과 매일 큰 정신으로 씨름하는 사람들에게 동의하지 않습니다. 현명한 사람은 그것을 견디겠지만 선택하지는 않을 것입니다. 전쟁보다는 평화를 선택할 것입니다."
>
> -세네카, 《도덕 서한》, 28.7

::: {.callout-note title="2월 12일: 나는 마음의 평화를 무엇과 바꿨는가?" icon="false"}
<br/>
<br/>
<br/>
:::

::: {.callout-note title="2월 13일: 나의 쾌락 중 어떤 것이 실제로는 벌인가?" icon="false"}
<br/>
<br/>
<br/>
:::

::: {.callout-note title="2월 14일: 내 안의 작은 목소리에 더 잘 귀 기울이는 방법은 무엇일까?" icon="false"}
<br/>
<br/>
<br/>
:::

::: {.callout-note title="2월 15일: 이 강한 감정들이 과연 말이 되는가?" icon="false"}
<br/>
<br/>
<br/>
:::

::: {.callout-note title="2월 16일: 나는 무엇을 필요 이상으로 어렵게 만들고 있는가?" icon="false"}
<br/>
<br/>
<br/>
:::

::: {.callout-note title="2월 17일: 지금 당장 가질 수 있는 행복을 나는 미루고 있는가?" icon="false"}
<br/>
<br/>
<br/>
:::

# 8주차: 욕구를 줄이고 행복을 늘리세요

스토아 학파는 더 적게 원하는 것이 감사를 증가시키는 반면 더 많이 원하는 것은 감사를 없앤다는 것을 알았습니다. 에픽테토스는 그의 가르침의 많은 부분을 학생들이 더 많이 원하는 파괴적인 습관을 줄이는 데 도움을 주는 데 집중했습니다. 그는 그 안에서 행복한 삶과 관계의 열쇠를 보았습니다. 더 적게 원하는 기술을 실천하고 우리가 이미 우리 앞에 가지고 있는 부분에 감사함으로써 우리는 소위 쾌락의 쳇바퀴에서 뛰어내리고 진정한 만족의 삶으로 가는 길에 실제적인 발걸음을 내딛고 있습니다.

> "연회에서처럼 인생에서 행동하는 것을 기억하십시오. 무언가가 돌아서 당신에게 올 때 손을 뻗어 적당한 양을 취하십시오. 그것이 당신을 지나가나요? 멈추지 마십시오. 아직 오지 않았나요? 그것에 대한 욕망에 불타지 말고 당신 앞에 도착할 때까지 기다리십시오. 아이들 배우자 지위 부와 함께 이런 식으로 행동하십시오. 언젠가 그것은 당신을 신들과의 연회에 합당하게 만들 것입니다."
>
> -에픽테토스, 《엔키리디온》, 15

> "한 번에 하나씩 하십시오. 그리고 그것을 당신의 온 영혼으로 하십시오."
> —에픽테토스, 《담화록》, 2.19.29 (의역)

> "자유는 마음의 욕망을 채움으로써 확보되는 것이 아니라 욕망을 제거함으로써 확보된다."
>
> -에픽테토스, 《담화록》, 4.1.175

::: {.callout-note title="2월 21일: 나는 무엇을 갈망하는 것을 멈출 수 있을까?" icon="false"}
<br/>
<br/>
<br/>
:::

::: {.callout-note title="2월 22일: 내가 하고 싶은 말이 차라리 하지 않는 것이 낫다는 것을 확신하는가?" icon="false"}
<br/>
<br/>
<br/>
:::

::: {.callout-note title="2월 23일: 분노가 아무것도 바꾸지 못한다면 왜 사물에 화를 내는가?" icon="false"}
<br/>
<br/>
<br/>
:::

::: {.callout-note title="2월 24일: 왜 나는 해를 입었다고 스스로에게 말하고 있는가?" icon="false"}
<br/>
<br/>
<br/>
:::

::: {.callout-note title="2월 25일: 몇 달 후면 이 싸움을 기억이나 할까?" icon="false"}
<br/>
<br/>
<br/>
:::

# 9주차: 무관심을 기르다

어떤 사람들은 건강 부 쾌락 성취와 같은 좋은 것들을 쫓으며 평생을 보냅니다. 다른 사람들은 질병 가난 고통과 같은 나쁜 것들을 똑같은 에너지로 피하려고 노력합니다. 이것들은 두 가지 완전히 다른 접근 방식으로 보이지만 결국에는 같습니다. 스토아 학파는 우리가 바라고 피하는 많은 것들이 우리의 통제 밖에 있다는 것을 끊임없이 상기시켰습니다. 불가능한 것을 쫓는 대신 스토아 학파는 두 가지 조건 모두에서 번성할 수 있도록 동등하게 준비되고 동등하게 적합하도록 훈련했습니다. 그들은 무관심하도록 훈련했습니다. 이것은 위대한 힘이며 이 기술의 배양은 매우 강력한 수련입니다.

> "존재하는 모든 것들 중에서 어떤 것은 선하고 다른 것은 악하며 또 다른 것은 무관심하다. 선한 것은 미덕과 그것들을 공유하는 모든 것이고 악한 것은 악덕과 그것들에 빠지는 모든 것이며 무관심한 것은 미덕과 악덕 사이에 있으며 부 건강 삶 죽음 쾌락 고통을 포함한다."
>
> -에픽테토스, 《담화록》, 2.19.12B-13

> "나의 이성적인 선택은 이웃의 이성적인 선택에 대해 그의 숨결과 몸에 대해 무관심한 것과 같다. 우리가 협력을 위해 얼마나 많이 만들어졌든 우리 각자의 지배적인 이성은 자신의 일의 주인이다. 만약 그렇지 않다면 다른 사람의 악이 나의 해가 될 수 있으며 신은 다른 사람이 나의 불행을 통제하도록 의도하지 않았다."
>
> -마르쿠스 아우렐리우스, 《명상록》, 8.56

> "당신이 화가 났을 때 당신의 가장 큰 적은 당신 자신입니다."
> —세네카, 《분노에 대하여》, 3.12 (의역)
::: {.callout-note title="2월 26일: 왜 다른 사람이 실수한 것에 신경 써야 하는가?" icon="false"}
<br/>
<br/>
<br/>
:::

::: {.callout-note title="2월 27일: 중요하지 않은 것들에 대한 무관심을 어떻게 기를 수 있을까?" icon="false"}
<br/>
<br/>
<br/>
:::

::: {.callout-note title="2월 28일: 잠시 진정하면 어떻게 될까?" icon="false"}
<br/>
<br/>
<br/>
:::

::: {.callout-note title="3월 1일: 다른 사람들이 당연하게 여기는 것들을 얼마나 자주 의심하는가?" icon="false"}
<br/>
<br/>
<br/>
:::

::: {.callout-note title="3월 2일: 나는 나 자신을 정확하게 보고 평가하는가?" icon="false"}
<br/>
<br/>
<br/>
:::

::: {.callout-note title="3월 3일: 나는 철학자와 함께 서 있는가 아니면 군중과 함께 서 있는가?" icon="false"}
<br/>
<br/>
<br/>
:::

# 10주차: 비싼 물건의 대가

견유학파로부터 스토아학파는 사물의 진정한 가치(axia)에 초점을 맞추는 강력한 실천을 배웠습니다. 물건의 비용은 단순히 판매되는 가격이 아니라 소유자가 소유하는 데 드는 비용이라는 것입니다. 물질적 재화에 대한 우리의 욕망의 대부분은 불안과 평온의 상실이라는 큰 대가를 치르게 되며 심지어 얻었을 때에도 이러한 것들은 종종 우리를 더 불안하게 하고 덜 평온하게 만듭니다. 이번 주에는 여러분이 사는 물건들이 실제로 얼마의 비용이 드는지 성찰하는 시간을 가지십시오. 그것들이 정말로 여러분이 지불해 온 가치가 있는지 확인하십시오.

> "그러므로 우리가 추구하고 우리가 힘써 노력하는 것들에 관하여 우리는 이러한 고려를 해야 합니다. 즉 그들 안에는 유용한 것이 없거나 대부분은 유용하지 않다는 것입니다. 그들 중 일부는 불필요하고 다른 일부는 그다지 가치가 없습니다. 그러나 우리는 이것을 분별하지 못하고 그것들을 공짜로 여기지만 그것들은 우리에게 큰 대가를 치르게 합니다."
>
> -세네카, 《도덕 서한》, 42.6

> "만약 어떤 사람이 당신의 몸을 지나가는 사람에게 주었다면 당신은 격분할 것입니다. 그러나 당신은 당신의 마음을 다가오는 누구에게나 넘겨주어 그들이 당신을 학대하고 그것을 혼란스럽고 괴롭게 남겨두게 합니다. 그것에 대해 부끄러움이 없습니까?"
>
> -에픽테토스, 《엔키리디온》, 28

> "시노페의 디오게네스는 우리가 매우 가치 있는 것을 매우 가치 없는 것으로 팔고 그 반대도 마찬가지라고 말했다."
>
> -디오게네스 라에르티우스, 《저명한 철학자들의 생애》, 6.2.35B

::: {.callout-note title="3월 7일: 내 자신의 의견을 믿기 전에 시험해 볼 수 있을까?" icon="false"}
<br/>
<br/>
<br/>
:::

::: {.callout-note title="3월 10일: 나의 롤모델은 누구인가? 왜?" icon="false"}
<br/>
<br/>
<br/>
:::

::: {.callout-note title="3월 11일: 나는 어디에서 자유를 팔았는가? 어떻게 되찾을 수 있을까?" icon="false"}
<br/>
<br/>
<br/>
:::

# 11주차: 다른 사람의 관점에서 생각해보세요

우리는 우리 자신의 의도에 대해서는 최선을 다하고 다른 사람의 의도에 대해서는 최악을 가정하는 경향이 있습니다. 그러고 나서 우리는 왜 인생이 그렇게 갈등으로 가득 차 있는지 궁금해합니다! 스토아 학파는 이 습관을 뒤집어 자신의 첫 반응에 대해 의심하고 다른 사람에게는 먼저 동정심으로 접근하라고 스스로에게 상기시켰습니다。 권력 있는 사람들은 종종 놀라울 정도로 이런 식으로 행동하는 데 끔찍하지만 그의 통치 기간 동안 지구상에서 가장 강력한 사람이었던 마르쿠스 아우렐리우스는 다른 사람들을 대하는 그의 인간성으로 유명했습니다. 그는 항상 잠시 시간을 내어 자신의 실패를 기억하고 다른 사람이 상황을 어떻게 볼지 숙고하라고 스스로에게 말했습니다. 그는 우리처럼 대부분의 사람들이 최선을 다하고 있다는 것을 스스로에게 상기시켰습니다. 비록 그것이 일상생활의 거칠고 혼란스러운 속에서 간과하기 쉽지만 말입니다. 이번 주에는 그것을 기억하고 각 상호 작용을 우리 자신의 관점뿐만 아니라 다른 관점에서도 생각해 봅시다.

> "미래에 대해 걱정하지 마십시오. 만약 미래를 맞이해야 한다면 당신은 현재를 다루는 데 사용하는 바로 그 이성으로 무장하고 미래로 나아갈 것입니다."
> —마르쿠스 아우렐리우스, 《명상록》, 7.826

> "일어나는 일을 받아들이십시오. 그것은 우주의 질서의 일부입니다."
> —마르쿠스 아우렐리우스, 《명상록》, 4.23 (의역)
::: {.callout-note title="3월 12일: 다른 사람들의 좋은 의도를 찾는다면 무엇이 바뀔까?" icon="false"}
<br/>
<br/>
<br/>
:::

::: {.callout-note title="3월 13일: 불운이라고 부르는 대신 필연적인 것으로 볼 수 있을까?" icon="false"}
<br/>
<br/>
<br/>
:::

::: {.callout-note title="3월 14일: 나의 오만함이 배우는 것을 어떻게 방해하고 있는가?" icon="false"}
<br/>
<br/>
<br/>
:::

::: {.callout-note title="3월 15일: 만약 내가 현재 순간에만 완전히 집중한다면 어떨까?" icon="false"}
<br/>
<br/>
<br/>
:::

::: {.callout-note title="3월 17일: 내 선택은 아름다운가?" icon="false"}
<br/>
<br/>
<br/>
:::

::: {.callout-note title="3월 18일: 어떤 나쁜 가정을 버릴 수 있을까?" icon="false"}
<br/>
<br/>
<br/>
:::

# 12주차: 휴대용 휴양지

나는 미래에 즉 휴가 때 쉬는 날에 자연 속으로 나가기로 계획할 때 일상적인 삶의 요구의 압박으로부터 평화와 해방을 찾을 것이라고 생각합니다. 그러나 이것은 우리가 생각하는 것만큼 자주 일어나지 않는 것 같습니다, 그렇죠? 그리고 우리가 그 평화를 얻었을 때 우리가 다시 소동 속으로 돌아오면 그것을 유지하기가 어렵습니다. 스토아 학파에게 이 모든 것은 광기입니다. 진정한 휴양지는 우리 자신의 마음과 영혼의 자유로 우리가 이미 가지고 있는 선물들을 고려하는 것입니다. 그것들은 영원히 우리의 피난처가 될 수 있습니다. 우리가 매일 시간을 내어 그렇게 한다면 말입니다.

> "사람들은 시골 바닷가 또는 산에서 자신을 위한 휴양지를 찾습니다. 당신은 바로 그 똑같은 것들을 갈망하는 습관이 매우 강합니다. 그러나 이것은 전적으로 비천한 사람의 특징입니다. 왜냐하면 당신은 언제든지 당신 자신 안에서 그러한 휴양지를 찾을 수 있기 때문입니다. 왜냐하면 당신은 당신 자신의 영혼보다 더 평화롭고 덜 분주한 휴양지를 어디에서도 찾을 수 없기 때문입니다. 특히 자세히 살펴보면 그것이 편안함으로 가득 차 있다면 말입니다. 저는 그것이 잘 정돈된 것 이상이 아니라고 말합니다. 이 휴양지를 자주 즐기고 새로워지십시오."
>
> -마르쿠스 아우렐리우스, 《명상록》, 4.3.1

> "우리를 비하하고 예속시키는 것은 부와 지위에 대한 욕망뿐만 아니라 평화 여가 여행 학습에 대한 욕망이라는 것을 기억하십시오. 외부적인 것이 무엇이든 중요하지 않습니다. 우리가 그것에 부여하는 가치가 우리를 다른 것에 예속시킵니다... 우리의 마음이 있는 곳에 우리의 장애물이 있습니다."
>
> -에픽테토스, 《담화록》, 4.4.1-2; 15

> "당신의 지배적인 이성은 그것이 집결하고 자신에게 의존할 때 정복할 수 없게 된다는 것을 기억하십시오. 그래서 그것은 비록 그 입장이 비합리적일지라도 자신의 의지에 반하는 어떤 것도 하지 않을 것입니다. 만약 그 판단이 신중하고 이성적으로 내려진다면 얼마나 더 정복할 수 없겠습니까? 그러므로 열정에서 해방된 마음은 뚫을 수 없는 요새입니다. 사람은 영원히 더 안전한 피난처가 없습니다."
>
> -마르쿠스 아우렐리우스, 《명상록》, 8.48

::: {.callout-note title="3월 19일: 내 짜증의 진짜 원인은 무엇인가 - 외부적인 것인가 아니면 내 의견인가?" icon="false"}
<br/>
<br/>
<br/>
:::

::: {.callout-note title="3월 20일: 역경을 견딜 수 있게 해주는 미덕을 기르고 있는가?" icon="false"}
<br/>
<br/>
<br/>
:::

::: {.callout-note title="3월 21일: 먼 곳이 아닌 바로 지금 여기에서 평화를 찾는다면 어떨까?" icon="false"}
<br/>
<br/>
<br/>
:::

::: {.callout-note title="3월 22일: 나는 학교 교육과 교육을 혼동하고 있는가?" icon="false"}
<br/>
<br/>
<br/>
:::

::: {.callout-note title="3월 23일: 탐욕스러운 악덕을 어떻게 치료할 수 있을까? 내 병을 어떻게 고칠 수 있을까?" icon="false"}
<br/>
<br/>
<br/>
:::

::: {.callout-note title="3월 24일: 평범한 것들에서 어떤 철학적 교훈을 찾을 수 있을까?" icon="false"}
<br/>
<br/>
<br/>
:::

::: {.callout-note title="3월 25일: 욕구를 줄이면 더 부유하게 느껴질까?" icon="false"}
<br/>
<br/>
<br/>
:::

# 13주차: 감동시킬 필요성에 '아니오'라고 말하세요

다른 사람들에게 감동을 주고 호감을 얻고 싶은 욕망이 인간이라는 종에게 내재되어 있다면 소셜 미디어 이전에 태어난 모든 세대는 운이 좋았습니다. 오늘날 우리는 우리가 하고 있는 모든 인상적인 일 우리가 극복하고 있는 시련 우리가 피한 위험과 실현한 승리의 발표로 채워지기를 요구하는 끝없는 상태 업데이트의 흐름에 직면해 있습니다. 지치는 일입니다. 수 세기 전 에픽테토스는 그의 (컴퓨터 없는) 학생들에게서도 이러한 자부심과 자기애를 보았고 그것이 그렇게 순진하지 않다고 상기시켰습니다. 사실 그는 그것이 그들의 삶의 목적을 파괴하고 그들을 산만하게 하고 지치게 할 것이라고 말했습니다. 세네카 역시 관중의 승인을 구하는 것을 삶의 불명예 중 하나로 보았습니다. 이번 주에는 그러한 충동을 지켜보고 휴대폰과 상태 업데이트가 얼마나 필요한지 알아차린 다음 물어보십시오. 이것이 내가 되고 싶은 사람의 종류인가? 이것이 철학자가 할 일인가?

> "만약 당신이 누군가에게 감동을 주기 위해 당신의 의지를 당신의 통제 밖의 것들로 돌린다면 당신이 당신의 인생의 모든 목적을 망쳤다는 것을 확신하십시오. 그러므로 당신이 하는 모든 일에서 철학자가 되는 것에 만족하고 만약 당신이 또한 철학자로 보여지기를 원한다면 당신이 그렇다는 것을 먼저 자신에게 보여주면 당신은 성공할 것입니다."
>
> -에픽테토스, 《엔키리디온》, 23

> "공개적으로 당신의 업적과 위험에 대해 자주 그리고 과도하게 이야기하는 것을 피하십시오. 왜냐하면 당신이 당신의 위험을 이야기하는 것을 아무리 즐기더라도 다른 사람들이 당신의 일에 대해 듣는 것은 그다지 즐겁지 않기 때문입니다."
>
> -에픽테토스, 《엔키리디온》, 33.14

> "법정에서 죽어가는 숨을 거두고 고령에 알려지지 않은 소송 당사자들을 위해 변호하고 여전히 무지한 관중들의 승인을 구하는 변호사는 얼마나 불명예스러운가."
>
> -- 세네카, 《인생의 짧음에 대하여》, 20.2

::: {.callout-note title="3월 26일: 나는 경계를 늦추지 않고 있는가?" icon="false"}
<br/>
<br/>
<br/>
:::

::: {.callout-note title="3월 27일: 나는 어떤 귀중한 것들을 너무 싸게 팔고 있는가?" icon="false"}
<br/>
<br/>
<br/>
:::

::: {.callout-note title="3월 28일: 나의 훈련은 내가 상황에 대처하는 데 도움이 되도록 설계되었는가?" icon="false"}
<br/>
<br/>
<br/>
:::

::: {.callout-note title="3월 29일: 왜 나는 사람들에게 감동을 주는 것에 그렇게 신경을 쓰는가?" icon="false"}
<br/>
<br/>
<br/>
:::

::: {.callout-note title="3월 30일: 내가 이성에 의해 지배되지 않는다면 나는 무엇에 의해 지배되는가?" icon="false"}
<br/>
<br/>
<br/>
:::

::: {.callout-note title="3월 1일: 오늘 불가능한 것을 쫓는 것을 멈출 수 있을까?" icon="false"}
<br/>
<br/>
<br/>
:::

# 14주차: 잘못될 수 있는 것은 무엇인가

우리는 잘못될 수 있는 것에 대해 생각하는 사람들을 "비관론자"라고 부릅니다. 어떤 사람들은 나쁜 생각이 나쁜 사건을 끌어들인다고 생각하기도 합니다. 스토아 학파는 이 모든 것이 말도 안 된다고 생각했습니다. 사실 그들은 소위 최악의 시나리오에 대해 숙고하는 것을 구체적으로 장려하는 praemeditatio malorum(악의 사전 명상)이라는 관행을 가지고 있었습니다. 마르쿠스는 자신을 흥분시키기 위해서가 아니라 정반대로 자신을 진정시키고 집중시켜 반응하기보다는 올바른 방식으로 행동할 준비를 하기 위해 법정에서 보게 될 모든 추악함에 대해 생각하며 하루를 시작하곤 했습니다. 세네카 역시 보통 일어나는 일뿐만 아니라 일어날 수 있는 일에 대해서도 미리 명상하는 것을 실천했습니다. 에픽테토스는 사랑하는 사람에게 키스할 때마다 그를 잃는 것을 상상하기까지 했습니다. 스토아 학파는 우리가 가진 모든 것이 행운으로부터 빌린 것이며 부정적인 시각화는 예상치 못한 것에 대한 우리의 인식을 높이는 데 도움이 된다고 믿었습니다. 당신의 생각에서 이것을 피하지 마십시오.

> "아침에 처음 일어날 때 자신에게 말하십시오. 나는 참견하기 좋아하는 사람 은혜를 모르는 사람 자기중심적인 사람 거짓말쟁이 질투하는 사람 괴짜를 만날 것이다. 그들은 모두 선과 악의 차이를 모르기 때문에 이러한 고통에 시달린다. 나는 선의 아름다움과 악의 추함을 이해했기 때문에 이러한 악행자들이 여전히 나와 비슷하다는 것을 안다... 그리고 아무도 나에게 해를 끼치거나 추함에 연루시킬 수 없으며 나는 내 친척에게 화를 내거나 그들을 미워할 수 없다. 우리는 협력을 위해 만들어졌기 때문이다."
>
> -마르쿠스 아우렐리우스, 《명상록》, 2.1

> "예상치 못한 것은 재앙의 무게를 더하고 놀라움은 사람의 고통을 증가시키지 않은 적이 없습니다. 그러므로 우리에게는 결코 예상치 못한 것이 있어서는 안 됩니다. 우리의 마음은 모든 것에 미리 보내져야 하며 우리는 단지 사물의 정상적인 과정뿐만 아니라 실제로 일어날 수 있는 일을 고려해야 합니다. 왜냐하면 인생에서 행운이 기뻐한다면 그녀의 높은 말에서 떨어뜨리지 않을 것이 있습니까?"
>
> -세네카, 《도덕 서한》, 91.3A-4

::: {.callout-note title="4월 4일: 오늘 철학이 나에게 원하는 사람이 되기 위해 싸울 수 있을까?" icon="false"}
<br/>
<br/>
<br/>
:::

::: {.callout-note title="4월 5일: 내 의견과 초기 반응을 확인하기 위해 잠시 멈춘다면 어떻게 될까?" icon="false"}
<br/>
<br/>
<br/>
:::

::: {.callout-note title="4월 6일: 사람들이 하는 최악의 일에도 불구하고 나는 그들을 어쨌든 사랑할 수 있을까?" icon="false"}
<br/>
<br/>
<br/>
:::

::: {.callout-note title="4월 7일: 내 의견이 문제의 일부인 곳은 어디인가?" icon="false"}
<br/>
<br/>
<br/>
:::

::: {.callout-note title="4월 8일: 나는 어떤 나쁜 가정, 습관, 또는 조언을 받아들였는가?" icon="false"}
<br/>
<br/>
<br/>
:::

# 15주차: 인상을 시험하라

에픽테토스의 주요 가르침 중 하나는 우리의 모든 인상 즉 우리가 우리 앞에 발견하는 모든 경험 인식 또는 상황을 시험하는 것에 관한 것이었습니다. 그는 이 실천을 강조하기 위해 담화록에서 열 번 엔키리디온의 서두에서 한 번 핵심 동사 dokimázo를 사용합니다. 이 단어는 순금속과 동전의 진위를 확인하기 위해 시험하는 감정사의 의미를 담고 있습니다. 가장 기억에 남는 용법 중 하나에서 에픽테토스는 우리가 인상을 시험해야 할 필요성을 동전으로 하는 것과 비교하고 숙련된 상인이 위조 동전이 테이블에 던져지는 소리를 들을 수 있는 것처럼 음악가가 불협화음을 감지할 수 있는 것과 같다고 말합니다. 이번 주에는 우리 앞에 오는 모든 것을 감정하는 수련을 해봅시다. 우리가 그렇지 않다는 것을 증명할 수 있을 때까지 모든 것이 위조되거나 오해의 소지가 있다고 가정합시다.

> "돈에 관해서는 우리가 명확한 관심을 느끼는 곳에서는 시험관이 가치를 발견하기 위해 많은 수단을 사용하는 완전한 기술이 있습니다... 우리가 우리를 잘못 인도할 수 있는 것들을 판단하는 데 큰 주의를 기울이는 것처럼 말입니다. 그러나 우리 자신의 지배 원리에 관해서는 우리는 하품하고 졸며 비용을 계산하지 않고 스쳐 지나가는 어떤 외양이라도 받아들입니다."
> —에픽테토스, 《담화록》, 1.20.8; 11

> "우선 인상의 힘에 휩쓸리지 마십시오. 그것에게 '잠깐만 기다려, 네가 누구이고 어디서 왔는지 보자. 너를 시험해 보겠다'고 말하십시오..."
> —에픽테토스, 《담화록》, 2.18.24

> "처음부터 모든 가혹한 인상에 대해 '당신은 인상일 뿐, 보이는 것과는 전혀 다르다'고 말하는 것을 습관으로 삼으십시오. 다음으로 당신이 소유한 규칙, 그중 첫 번째이자 가장 위대한 규칙인 이것, 즉 그것이 우리의 통제하에 있는 것에 속하는지 아닌지에 따라 그것을 검토하고 시험하십시오. 만약 후자라면 '그것은 나에게 아무것도 아니다'라고 대답할 준비를 하십시오."
> — 에픽테토스, 《엔키리디온》, 1.5

::: {.callout-note title="4월 9일: 한 걸음 물러서서 내 인상을 시험해 볼 수 있을까? 만약 그렇게 한다면 무엇을 발견할까?" icon="false"}
<br/>
<br/>
<br/>
:::

::: {.callout-note title="4월 10일: 내 판단이 나에게 어떻게 고뇌를 일으키는가?" icon="false"}
<br/>
<br/>
<br/>
:::

::: {.callout-note title="4월 11일: 내가 이미 안다고 생각하는 것을 멈추고 여기서 무언가를 배울 수 있을까?" icon="false"}
<br/>
<br/>
<br/>
:::

::: {.callout-note title="4월 14일: 나는 내 사업의 대차대조표보다 내 삶의 균형을 더 잘 맞추고 있는가?" icon="false"}
<br/>
<br/>
<br/>
:::

# 16주차: 충동 조절

무언가가 당신을 화나게 한다면 여기에 쓰고 그것을 보십시오. 무슨 일이 있었습니까? 누가 그것을 일으켰습니까? 이제 당신의 반응에 대해 생각해 보십시오. 당신은 무엇을 말했습니까? 당신은 무엇을 느꼈습니까? 이것이 그것을 더 좋게 만들었습니까 아니면 더 나쁘게 만들었습니까? 황제로서 마르쿠스 아우렐리우스는 분명히 화를 낼 많은 사람들과 원인이 있었습니다. 그는 또한 실제적인 권력과 권위를 가지고 있었습니다. 그럼에도 불구하고 우리는 그가 자신에게 "당신은 당신의 마음에 대한 힘을 가지고 있습니다. 외부 사건이 아닙니다. 이것을 깨달으면 힘을 찾을 것입니다."라고 말했을 것이라는 것을 발견합니다. 당신에게 일어난 일도 마찬가지입니다. 당신은 일어난 일을 통제하지 않았지만 그 여파로 당신이 따르는 충동을 통제합니다.

> "에픽테토스는 우리가 동의의 잃어버린 기술을 발견해야 하며 우리의 충동의 영역에 특별한 주의를 기울여야 한다고 말합니다. 즉 그것들은 유보의 대상이 되고 공동선에 종속되며 실제 가치에 비례한다는 것입니다."
> —마르쿠스 아우렐리우스, 《명상록》, 11.37

> "당신은 행운이 모든 구석에서 당신을 만났다고 말합니다. 그러나 행운의 사람은 자신에게 행운을 주는 사람입니다. 그리고 행운은 잘 조율된 영혼, 좋은 충동, 그리고 좋은 행동입니다."
> —마르쿠스 아우렐리우스, 《명상록》, 5.36

> "당신의 thoughts를 이렇게 구성하십시오. 당신은 늙은 사람입니다. 당신은 더 이상 이것에 의해 노예가 되지 않을 것이며, 더 이상 모든 충동에 의해 꼭두각시처럼 끌려다니지 않을 것이며, 당신의 현재 운명에 대해 불평하거나 미래를 두려워하는 것을 멈출 것입니다."
> —마르쿠스 아우렐리우스, 《명상록》, 2.2

::: {.callout-note title="4월 16일: 오늘 나는 무엇에 더 주의를 기울일 수 있을까?" icon="false"}
<br/>
<br/>
<br/>
:::

::: {.callout-note title="4월 17일: 사소한 일에 일일이 상처받는 것을 멈출 수 있을까?" icon="false"}
<br/>
<br/>
<br/>
:::

::: {.callout-note title="4월 18일: 이것에 대해 의견을 가질 필요가 있을까?" icon="false"}
<br/>
<br/>
<br/>
:::

::: {.callout-note title="4월 20일: 진정한 선은 몇 가지인가?" icon="false"}
<br/>
<br/>
<br/>
:::

::: {.callout-note title="4월 21일: 주의력이 흐트러지지 않고 얼마나 오래 버틸 수 있을까?" icon="false"}
<br/>
<br/>
<br/>
:::

::: {.callout-note title="4월 22일: 나는 자기 인식적이고 자기 비판적이며 자기 결정적인가?" icon="false"}
<br/>
<br/>
<br/>
:::

# 17주차: 경멸의 자유

우리가 사물을 묘사하는 데 사용하는 언어는 그 사물에 가치를 부여합니다. 우리는 종종 우리가 사거나 입거나 먹거나 마시는 것에 대한 우리의 선택이 실제보다 훨씬 더 좋아 보이도록 하기 위해 최상급으로 우리의 언어를 꾸밉니다. 황제로서 마르쿠스 아우렐리우스는 어떤 식사에서든 그의 식탁에 최고급 팔레르니아 와인을 올릴 수 있었지만 그는 그것이 단지 포도 주스일 뿐이라고 스스로에게 상기시키는 것을 선호했습니다. 황제로서 그는 보라색 망토를 입을 수 있는 유일한 로마인이었지만 그는 그의 망토가 다른 망토와 같고 단지 보라색 색조를 내기 위해 조개류 피로 염색되었을 뿐이라고 지적하는 수고를 했습니다. 이번 주에는 약간의 경멸로 자신의 사치품과 갈망하는 것들을 깎아내리는 연습을 하십시오. 가능한 한 가장 무뚝뚝한 언어로 그것들을 묘사하고 그것들이 당신에게 미치는 힘이 얼마나 줄어드는지 보십시오.

> "고기나 다른 음식이 우리 앞에 놓일 때 우리가 생각하는 것처럼 이것은 죽은 물고기, 죽은 새, 또는 돼지입니다. 또한 이 고급 와인은 단지 포도 한 송이의 주스일 뿐이고, 이 보라색 가장자리가 있는 로브는 조개류의 피 약간에 염색된 양모일 뿐입니다. 또는 성관계에 대해, 그것은 단지 성기를 함께 문지른 후 경련성 분비물이 나오는 것일 뿐입니다. 같은 방식으로 우리의 인상은 실제 사건을 포착하고 스며들어 우리가 그것들을 있는 그대로 볼 수 있도록 합니다."
> —마르쿠스 아우렐리우스, 《명상록》, 6.13

> "어떤 것에 대해 분노와 원한으로 불타올랐던 사람들, 심지어 성공, 불행, 악행, 또는 어떤 특별한 구별로 가장 유명했던 사람들의 목록을 마음속에 간직하십시오. 그러고 나서 자신에게 물어보십시오. 그것은 어떻게 되었습니까? 연기와 먼지, 전설이 되려고 노력하는 단순한 신화의 재료......"
> —마르쿠스 아우렐리우스, 《명상록》, 12.27
> "당신은 와인과 리큐어 맛이 어떤지 압니다. 백 병이든 천 병이든 당신의 방광을 통과하는 것은 아무런 차이가 없습니다. 당신은 필터에 지나지 않습니다."
> —세네카, 《도덕 서한》, 77.16

::: {.callout-note title="4월 23일: 나는 내 마음을 어떻게 돌보고 있는가?" icon="false"}
<br/>
<br/>
<br/>
:::

::: {.callout-note title="4월 24일: 멋진 차, 보석, 고급 와인 - 이것들은 정말 무엇인가?" icon="false"}
<br/>
<br/>
<br/>
:::

::: {.callout-note title="4월 25일: 내가 틀렸을 때 인정할 의향이 있는가?" icon="false"}
<br/>
<br/>
<br/>
:::

::: {.callout-note title="4월 26일: 스파링 파트너에게서 무엇을 배울 수 있을까?" icon="false"}
<br/>
<br/>
<br/>
:::

::: {.callout-note title="4월 27일: 칭찬은 어차피 얼마나 오래 지속되는가?" icon="false"}
<br/>
<br/>
<br/>
:::

::: {.callout-note title="4월 28일: 나의 모든 욕망이 나에게서 어떤 힘을 빼앗아 가는가?" icon="false"}
<br/>
<br/>
<br/>
:::

::: {.callout-note title="4월 29일: 하늘을 올려다볼 때 나는 무엇을 느끼는가?" icon="false"}
<br/>
<br/>
<br/>
:::

# 18주차: 말하지 말고 보여주세요

삶의 기술은 우리가 암기할 수 있는 일련의 가르침이나 공식이 아닙니다. 그것은 끊임없는 노력을 요구하는 실천입니다. 에픽테토스는 학생들에게 강의실에서 들었거나 책에서 읽은 것을 앵무새처럼 되뇌지 말고 실천에 옮기라고 끊임없이 상기시켰습니다。 그는 볼 수 있는 진보가 선언된 어떤 것보다 낫다는 것을 알았습니다. 이번 주 여러분의 글이 여러분이 계획하거나 생각하는 것이 아니라 여러분이 한 일과 하고 있는 일을 보여주게 하십시오. 그것이 여러분의 행동 즉 선한 행동의 목록이 되게 하십시오.

> "단순한 이론을 받은 사람들은 즉시 그것을 토해내고 싶어 합니다. 마치 배탈이 난 위가 음식을 토해내는 것처럼 말입니다. 먼저 당신의 이론을 소화하면 토하지 않을 것입니다. 그렇지 않으면 그것들은 날것이고 상하고 영양가가 없을 것입니다. 그것들을 소화한 후에 체조 선수들의 어깨가 그들의 식단과 훈련을 보여주는 것처럼, 그리고 장인의 기술이 그들이 배운 것을 보여주는 것처럼 당신의 이성적인 선택의 변화를 우리에게 보여주십시오."
> — 에픽테토스, 《담화록》, 3.21.1-3

> "먼저 사람들이 당신이 누구인지 모르게 하는 연습을 하십시오. 당신의 철학을 잠시 동안 자신에게만 간직하십시오. 과일이 생산되는 방식과 똑같이 씨앗은 한 계절 동안 묻혀 숨겨져 점차 자라서 완전히 성숙하게 됩니다. 그러나 곡식이 줄기가 완전히 발달하기 전에 싹을 틔우면 결코 익지 않을 것입니다.... 당신은 그런 종류의 식물입니다. 너무 빨리 열매를 보이고 겨울이 당신을 죽일 것입니다."
> —세네카, 《담화록》, 4.8.35B-37
::: {.callout-note title="4월 30일: 내 행동이 내 성격과 일치하는가?" icon="false"}
<br/>
<br/>
<br/>
:::

::: {.callout-note title="5월 1일: 내 행동과 내 마음이 내 철학과 일치하는가?" icon="false"}
<br/>
<br/>
<br/>
:::

::: {.callout-note title="5월 2일: 나는 어떤 종류의 사람이 되고 싶은가?" icon="false"}
<br/>
<br/>
<br/>
:::

::: {.callout-note title="5월 5일: 나는 나 자신을 평생의 프로젝트로 삼았는가?" icon="false"}
<br/>
<br/>
<br/>
:::

# 19주차: 우리는 습관의 산물이다

로마 스토아 학파는 삶의 기술에서 진보를 이루기 위해 습관적인 행동을 다루는 데 큰 중점을 두었습니다. 위대한 로마 스토아 교육자 무소니우스 루푸스는 세상의 모든 이론이 좋은 습관을 이길 수 없다고(또는 나쁜 습관을 극복할 수 없다고) 주장했습니다. 에픽테토스는 습관에 대한 이러한 초점에서 무소니우스를 따랐으며 분노와 같은 나쁜 습관을 강화하지 않고 더 나은 습관으로 대체할 방법을 찾는 데 중점을 두었습니다. 우리 모두는 다른 사람에게서 나쁜 습관을 볼 때 그것을 인식하지만 우리 자신에게서 그것을 보는 것은 조금 더 어렵습니다. 이번 주에는 당신을 방해하는 습관이나 반복적인 행동에 대해 명상하십시오. 심지어 가까운 사람에게 도움을 요청하십시오.

> "모든 습관과 능력은 그에 상응하는 행동, 즉 걷기로 걷고 달리기로 달리는 것으로 확인되고 성장합니다... 그러므로 무언가를 하고 싶다면 습관으로 만드십시오. 그것을 하고 싶지 않다면 하지 말고 대신 다른 것을 습관으로 만드십시오. 같은 원리가 우리의 마음 상태에도 작용합니다. 화를 내면 그 악을 경험했을 뿐만 아니라 나쁜 습관을 강화하여 불에 기름을 부은 것입니다."
> — 에픽테토스, 《담화록》, 2.18.1-5

> "만약 당신이 성급한 사람이 되고 싶지 않다면 당신의 습관을 키우지 마십시오. 첫 단계로 침착함을 유지하고 화를 내지 않은 날을 세어보십시오. 나는 매일 화를 냈지만 이제는 격일로, 그다음에는 3일이나 4일에 한 번씩... 만약 당신이 30일까지 해낸다면 신에게 감사하십시오! 왜냐하면 습관은 먼저 약해지고 그다음에는 사라지기 때문입니다. 당신이 '나는 오늘 또는 다음 날 또는 3, 4개월 동안 화를 내지 않았고 도발에도 침착함을 유지했다'고 말할 수 있을 때 당신은 더 나은 건강 상태에 있다는 것을 알게 될 것입니다."
> —에픽테토스, 《담화록》, 2.18.11B-14
> "습관과의 싸움에서 어떤 도움을 찾을 수 있을까? 반대를 시도해 보라!"
> —에픽테토스, 《담화록》, 1.27.4

::: {.callout-note title="5월 8일: 내 자신의 선택에서 어떤 악이 나오는가?" icon="false"}
<br/>
<br/>
<br/>
:::

::: {.callout-note title="5월 9일: 나는 오늘을 붙잡을 것인가?" icon="false"}
<br/>
<br/>
<br/>
:::

::: {.callout-note title="5월 12일: 무슨 일이 있어도 친절하게 반응한다면 어떻게 될까?" icon="false"}
<br/>
<br/>
<br/>
:::

::: {.callout-note title="5월 13일: 나는 어떤 나쁜 습관에 기름을 붓고 있는가?" icon="false"}
<br/>
<br/>
<br/>
:::

# 20주차: 당신의 축복을 세어보세요

우리 삶에 없는 것들에 대해 불평하기는 쉽고 우리가 이미 가지고 있는 것에 대해 감사하기는 훨씬 더 어렵습니다. 세네카는 우리가 행복하기 위해 필요한 모든 것이 바로 우리 앞에 있으며 우리가 놓치고 있을지도 모르는 사치품들은 그 자체로 큰 대가를 치르게 될 것이라고 상기시켰습니다. 즉 우리가 이미 가지고 있는 것의 대가로 말입니다. 마르쿠스는 이에 동의했고 우리 삶에 존재하는 축복들을 세고 그것들이 없다면 어떨지(그리고 우리가 그것들을 얼마나 그리워할지) 상상하라고 스스로에게 상기시켰습니다. 이번 주에는 당신의 축복을 나열하고 당신이 운 좋게 가지고 있고 즐기는 것을 의식적으로 기록하여 에픽테토스가 말했듯이 그것들이 어디서 왔는지 명확하게 보고 그것에 대한 감사의 마음을 느낄 수 있도록 하십시오.

> "당신이 배운 기술, 당신이 훈련받은 기술을 사랑하고 그것에서 안식을 찾으십시오. 당신의 온 영혼으로 당신이 가진 모든 것을 신들에게 맡기고 당신 자신을 어떤 사람의 폭군이나 노예로 만들지 않는 사람으로 인생의 나머지를 통과하십시오."
> —마르쿠스 아우렐리우스, 《명상록》, 4.31

> "우주를 창조하고 우리에게 삶의 법칙을 부여하신 분은 우리가 사치스럽지 않게 잘 살도록 하셨습니다. 우리의 안녕에 필요한 모든 것은 바로 우리 앞에 있지만, 사치가 요구하는 것은 많은 비참함과 불안으로 모아집니다. 자연의 이 선물을 사용하고 그것을 가장 위대한 것들 중 하나로 칩시다."
> —세네카, 《도덕 서한》, 119.15B

> "만약 당신이 두 가지 자질, 즉 각 경우에 실제로 일어난 일에 대한 완전한 시각과 감사의 마음을 가지고 있다면 일어날 수 있는 어떤 일에 대해서도 섭리를 찬양하기 쉽습니다. 감사 없이는 보는 것의 의미가 무엇이며 보는 것 없이는 감사의 대상이 무엇입니까?"
> —에픽테토스, 《담화록》, 1.6.1-2
::: {.callout-note title="5월 14일: 내 행동이 나의 안녕에 기여하고 있는가?" icon="false"}
<br/>
<br/>
<br/>
:::

::: {.callout-note title="5월 15일: 지금 당장 셀 수 있는 축복은 무엇인가?" icon="false"}
<br/>
<br/>
<br/>
:::

::: {.callout-note title="5월 16일: 나는 좋은 습관을 위한 추진력을 어떻게 만들고 있는가?" icon="false"}
<br/>
<br/>
<br/>
:::

::: {.callout-note title="5월 17일: 나는 진보의 길에 있는가?" icon="false"}
<br/>
<br/>
<br/>
:::

::: {.callout-note title="5월 18일: 내 관심이 실제로 당면한 일에 있는가?" icon="false"}
<br/>
<br/>
<br/>
:::

::: {.callout-note title="5월 19일: 나는 내가 해야 할 일과 반대되는 일을 어디에서 하고 있는가?" icon="false"}
<br/>
<br/>
<br/>
:::

# 21주차: 진정한 기쁨을 실천하라

스토아 학파는 기쁨(chara)을 일상생활에서 실천할 가치가 있는 좋은 열정 중 하나로 여겼습니다. 그러나 스토아적 기쁨은 감각의 즐거움이나 물질적 쾌락에 관한 것이 아닙니다. 마르쿠스에게 기쁨은 다른 사람에게 친절하게 대하는 것이었습니다. 세네카에게 그것은 고통과 죽음에 대한 두려움으로부터의 자유였습니다. 세네카가 말했듯이 데모크리토스와 함께 웃고 기쁨으로 우리의 "적절한" 인간의 일에 참여합시다. 이번 주 글에서 어디에서 기쁨을 찾을 수 있고 그것으로 어떤 선을 행할 수 있는지 생각해 보십시오.

> "당신은 당신의 방황의 범위에서 당신이 논리 부 명성 또는 어떤 방종에서도 삶의 기술을 찾지 못했다는 증거를 가지고 있습니다. 어디에도 없습니다. 그렇다면 어디에 있습니까? 인간 본성이 요구하는 것을 하는 데 있습니다. 사람은 어떻게 이것을 할 수 있습니까? 원칙이 욕망과 행동의 원천이 되게 함으로써입니다. 어떤 원칙입니까? 선과 악에 관한 원칙, 실제로 정의 자제 용기 자유를 창조하는 것 외에는 인간에게 선이 없으며 이러한 것들을 파괴하는 것 외에는 악이 없다는 믿음입니다."
> —마르쿠스 아우렐리우스, 《명상록》, 8.1.(5)
> "저를 믿으세요, 진정한 기쁨은 진지한 것입니다. 매력적인 표현으로 누군가가 가벼운 마음으로 죽음을 가볍게 여길 수 있다고 생각하십니까? 아니면 가난의 문을 활짝 열고 쾌락을 억제하거나 고통의 인내에 대해 명상할 수 있다고 생각하십니까? 이러한 생각을 편안하게 뒤집는 사람은 진정으로 기쁨으로 가득 차 있지만 거의 쾌활하지는 않습니다. 제가 당신이 소유하기를 바라는 것은 바로 그러한 기쁨입니다. 왜냐하면 당신이 그 근원을 주장하고 나면 결코 마르지 않을 것이기 때문입니다."
> —세네카, 《도덕 서한》, 23.4
> "헤라클레이토스는 대중 앞에 나설 때마다 눈물을 흘렸고 데모크리토스는 웃었습니다. 한 사람은 전체를 비참함의 행렬로 보았고 다른 한 사람은 어리석음의 행렬로 보았습니다. 그러므로 우리는 사물을 더 가볍게 보고 쉬운 마음으로 견뎌야 합니다. 왜냐하면 인생을 한탄하는 것보다 웃는 것이 더 인간적이기 때문입니다."
> —세네카, 《마음의 평온에 대하여》, 15.2
::: {.callout-note title="5월 21일: 나는 타격을 받고 링에 머물 수 있을까?" icon="false"}
<br/>
<br/>
<br/>
:::

::: {.callout-note title="5월 22일: 나는 바로 여기, 바로 지금 좋은 사람이 될 수 있을까?" icon="false"}
<br/>
<br/>
<br/>
:::

::: {.callout-note title="5월 23일: 나는 바로 여기, 바로 지금 살기 시작할 수 있을까?" icon="false"}
<br/>
<br/>
<br/>
:::

::: {.callout-note title="5월 24일: 어떻게 하면 나만의 행운을 만들 수 있을까?" icon="false"}
<br/>
<br/>
<br/>
:::

::: {.callout-note title="5월 25일: 어떤 종류의 이타적인 일이 나에게 기쁨을 가져다줄까?" icon="false"}
<br/>
<br/>
<br/>
:::

::: {.callout-note title="5월 26일: 다른 사람들이 어떻게 생각하는지 신경 쓰지 않는다면 어떨까?" icon="false"}
<br/>
<br/>
<br/>
:::

# 22주차: 위에서 본 풍경

일상적인 존재의 사소한 걱정과 근심에서 벗어나는 방법은 시간을 내어 스토아 학파가 "위에서 본 풍경"이라고 부르는 것을 얻는 것입니다. 이것은 마르쿠스 아우렐리우스가 정기적으로 스스로에게 상기시킨 것이었습니다. 그는 헤라클레이토스로부터 세상의 모든 것이 끊임없이 변하고 있으며 이것을 기억하는 것이 많은 스트레스와 걱정을 없앨 수 있다는 것을 배웠습니다. 이번 주에는 당신의 삶에서 다루고 있는 것을 가까이서만 보지 말고 멀리서도 보려고 노력하십시오. 당신의 문제 당신의 걱정 당신의 집착에 대한 다른 더 큰 관점이 어떻게 보일지 묘사해 보십시오.

> "플라톤이 얼마나 아름답게 표현했는가. 사람들에 대해 이야기하고 싶을 때마다 새의 눈으로 보고 모든 것을 한 번에 보는 것이 가장 좋다. 모임, 군대, 농장, 결혼과 이혼, 출생과 죽음, 시끄러운 법정이나 조용한 공간, 모든 외국인, 휴일, 기념관, 시장 등 모든 것이 함께 섞여 반대의 쌍으로 배열되어 있다."
> —마르쿠스 아우렐리우스, 《명상록》, 7.48
> "별들의 운행을 지켜보고 그들과 함께 달리는 자신을 상상해 보십시오. 원소들이 서로 변하는 것을 끊임없이 생각하십시오. 그러한 생각은 지상 생활의 먼지를 씻어냅니다."
> —마르쿠스 아우렐리우스, 《명상록》, 7.47
> "우주의 질서 - 모든 사람에게 동일한 - 는 어떤 신이나 인간에 의해 만들어진 것이 아니라 항상 있었고 항상 있을 것입니다. 영원한 불, 적절한 양으로 타오르고 적절한 양으로 꺼집니다."
>
> -헤라클레이토스 (알렉산드리아의 클레멘스가 인용한 바에 따름)

::: {.callout-note title="5월 28일: 행동을 취하기 전에 무엇을 생각해야 할까?" icon="false"}
<br/>
<br/>
<br/>
:::

::: {.callout-note title="5월 29일: 어떤 일이 내 마음을 살찌우는가?" icon="false"}
<br/>
<br/>
<br/>
:::

::: {.callout-note title="5월 30일: 나의 노력이 올바른 목적을 위한 것인가?" icon="false"}
<br/>
<br/>
<br/>
:::

::: {.callout-note title="5월 31일: 나의 소명이 좋은 사람이 되는 것이라면 나는 좋은 일을 하고 있는가?" icon="false"}
<br/>
<br/>
<br/>
:::

::: {.callout-note title="6월 1일: 모든 일에 대해 예비 방안을 염두에 두고 있는가?" icon="false"}
<br/>
<br/>
<br/>
:::

::: {.callout-note title="6월 2일: 나는 어디에서 나무만 보고 숲을 보지 못했는가?" icon="false"}
<br/>
<br/>
<br/>
:::

::: {.callout-note title="6월 3일: 나는 내 예비 계획에 대한 예비 계획을 가지고 있는가?" icon="false"}
<br/>
<br/>
<br/>
:::

# 23주차: 롤모델

입양은 로마 사회 특히 원로원 계급과 황제 계승을 위한 조항으로 널리 퍼진 관행이었습니다. 마르쿠스 아우렐리우스 자신도 안토니누스 피우스 황제의 양아들이었고 안토니누스 피우스 자신도 하드리아누스 황제에게 입양되어 마르쿠스가 언젠가 그들 둘을 계승하여 자색 옷을 입게 되었습니다. 세네카는 결코 입양되지 않았지만 그의 형 노바투스는 입양되어 신약성서에서 성 바울에 대한 고발을 거부한 갈리오가 되었습니다. 그러나 세네카는 입양 현상을 다른 관점에서 보는 것을 좋아했으며 우리는 항상 우리가 누구의 자녀가 되고 싶은지 선택할 수 있다고 말했습니다. 그에게는 공화국을 옹호하며 율리우스 카이사르에게 격렬하게 항의했던 우뚝 솟고 단호한 스토아 철학자 카토가 항상 그의 마음속에 서 있었습니다. 마르쿠스 아우렐리우스의 《명상록》 첫 번째 책은 그가 배운 모든 사람들과 그들의 삶에서 얻은 교훈의 목록입니다. 이번 주에는 당신이 따를 수 있는 모델 당신이 자신을 비교할 수 있는 현명하고 존경할 만한 사람들을 생각하는 데 사용하십시오.

> "우리는 부모를 선택할 수 없다고 말하기를 좋아합니다. 그들은 우연히 주어졌다고 말입니다. 그러나 우리는 진정으로 누구의 자녀가 되고 싶은지 선택할 수 있습니다."
> — 세네카, 《인생의 짧음에 대하여》, 15.3A
> "우리가 잘못을 저지르려고 할 때 증인이 옆에 서 있다면 대부분의 죄를 없앨 수 있습니다. 영혼은 존경할 수 있는 사람을 가져야 하며 그 사람의 모범으로 내면의 성소를 더욱 신성불가침하게 만들 수 있습니다. 다른 사람을 개선할 수 있는 사람은 행복합니다. 현재뿐만 아니라 생각 속에서도 말입니다!"
> —세네카, 《도덕 서한》, 11.9
::: {.callout-note title="6월 4일: 나는 내가 얼마나 강인하고 강할 수 있는지 깨닫고 있는가?" icon="false"}
<br/>
<br/>
<br/>
:::

::: {.callout-note title="6월 5일: 누군가에게 코를 풀어달라고 부탁하는 대신 내 코를 풀 수 있을까?" icon="false"}
<br/>
<br/>
<br/>
:::

::: {.callout-note title="6월 6일: 지금은 버텨야 할 때인가 아니면 그만둬야 할 때인가?" icon="false"}
<br/>
<br/>
<br/>
:::

::: {.callout-note title="6월 8일: 만약 내가 인내심을 갖고 한 걸음씩 나아간다면 무엇을 정복할 수 있을까?" icon="false"}
<br/>
<br/>
<br/>
:::

::: {.callout-note title="6월 9일: 지금 당장 싹을 잘라야 할 것은 무엇인가?" icon="false"}
<br/>
<br/>
<br/>
:::

::: {.callout-note title="6월 10일: 다른 사람이 할 만큼 강했다면 왜 나는 못하는가?" icon="false"}
<br/>
<br/>
<br/>
:::

# 24주차: 다른 손잡이를 사용해 보세요

에픽테토스는 그의 핸드북인 엔키리디온에서 어려운 사건에 대한 의사 결정 연습으로 스토아 학파가 사용하는 강력한 도구를 제공했습니다. 에픽테토스는 모든 것에는 두 가지 해석 즉 잡을 수 있는 손잡이가 있다고 말했습니다. 하나는 더 어렵게 만들고 다른 하나는 더 쉽게 만듭니다. 당신은 화를 냅니까? 아니면 공통점에 집중합니까? 잘못된 모든 것에 집중합니까? 아니면 잘된 것에 집중합니까? 이번 주에 보고 느끼는 모든 것에 대해 이러한 질문을 스스로에게 물어보십시오. 올바른 손잡이를 사용하고 있는지 확인하십시오.

> "모든 사건에는 두 개의 손잡이가 있습니다. 하나는 들 수 있는 손잡이이고 다른 하나는 들 수 없는 손잡이입니다. 만약 당신의 형제가 당신에게 잘못을 저지른다면 그의 잘못으로 그것을 잡지 마십시오. 왜냐하면 이것은 그것을 들어 올릴 수 없는 손잡이이기 때문입니다. 대신 다른 손잡이, 즉 그가 당신의 형제이고 당신이 함께 자랐다는 것을 사용하십시오. 그러면 당신은 들 수 있는 손잡이를 잡게 될 것입니다."
> —에픽테토스, 《엔키리디온》, 43
> "아니, 두려움을 일으키는 것은 사건이다. 다른 사람이 그것들을 지배하거나 막을 수 있을 때 그 사람은 두려움을 불러일으킬 수 있게 된다. 요새는 어떻게 파괴되는가? 철이나 불이 아니라 판단에 의해서... 여기서부터 시작해야 하며 이 전선에서 요새를 점령하고 폭군들을 몰아내야 한다."
> —에픽테토스, 《담화록》, 4.1.85-86; 87A
::: {.callout-note title="6월 11일: 분노가 그것을 일으킨 것보다 더 파괴적인 경우가 얼마나 많은가?" icon="false"}
<br/>
<br/>
<br/>
:::

::: {.callout-note title="6월 12일: 나는 적응하는 법을 배우고 있는가?" icon="false"}
<br/>
<br/>
<br/>
:::

::: {.callout-note title="6월 13일: 나는 이 인생의 캠페인에서 내 자리를 지키고 있는가 아니면 근무 중에 잠을 자고 있는가?" icon="false"}
<br/>
<br/>
<br/>
:::

::: {.callout-note title="6월 14일: 나는 이 상황의 올바른 손잡이를 잡고 있는가?" icon="false"}
<br/>
<br/>
<br/>
:::

::: {.callout-note title="6월 15일: 오늘 나는 더 많이 듣고 덜 말할 수 있을까?" icon="false"}
<br/>
<br/>
<br/>
:::

::: {.callout-note title="6월 16일: 나는 어디에서 도움이 필요한가? 누구에게 도움을 요청할 수 있을까?" icon="false"}
<br/>
<br/>
<br/>
:::

::: {.callout-note title="6월 17일: 나는 운이나 운명 탓으로 돌리고 있는 것이 실제로는 내 탓인 것은 무엇인가?" icon="false"}
<br/>
<br/>
<br/>
:::

# 25주차: 산책하기

세네카는 우리가 자주 방황하는 산책을 해야 한다고 믿었습니다. 왜냐하면 끊임없는 일은 우리의 마음을 산산조각 낼 것이기 때문입니다. (작가로서 그는 소설가 헬렌 던모어의 "글쓰기의 문제는 종종 긴 산책을 하면 명확해진다"는 말에 동의했을 것입니다.) 이번 주에는 좋은 산책을 하고 둔감함과 연약함이 사라지는 것을 지켜보십시오. 풍경을 즐기고 일에서 벗어나는 것을 즐기십시오. 그것들을 아침과 저녁 글쓰기 루틴의 일부로 만드십시오. 당신이 알고 있는 철학에 대해 일기를 쓰고 따를 준비가 된 자극받은 마음으로 돌아오십시오. 당신은 "휴식"을 취하고 있다고 생각하지만 실제로는 떠났을 때보다 더 똑똑하고 명확해집니다.

> "우리는 야외를 방황하며 산책해야 합니다. 그래야 마음이 야외 공기와 깊은 호흡으로 영양을 공급받고 상쾌해질 수 있습니다."
> —세네카, 《마음의 평온에 대하여》, 17.8
> "이 짧은 시간을 자연과 조화를 이루며 지나가고, 잘 익은 올리브가 떨어져 그것을 키운 땅을 찬양하고 그것을 자라게 한 나무에 감사하는 것처럼 우아하게 마지막 안식처에 이르십시오."
> —마르쿠스 아우렐리우스, 《명상록》, 4.48.2
> "마음에는 휴식이 주어져야 합니다. 좋은 휴식 후에는 개선되고 날카로워질 것입니다. 비옥한 밭은 결코 휴식을 주지 않으면 금방 비옥함을 잃기 때문에 강요해서는 안 되는 것처럼 모루 위에서 계속 일하면 마음의 힘이 부서질 것입니다. 그러나 잠시 동안 자유롭게 풀려나고 긴장을 풀면 힘을 되찾습니다. 계속 일하면 이성적인 영혼에 어떤 종류의 둔감함과 연약함이 생깁니다."
> —세네카, 《마음의 평온에 대하여》, 17.5
::: {.callout-note title="6월 18일: 나는 준비가 되어 있고 능력이 있는가?" icon="false"}
<br/>
<br/>
<br/>
:::

::: {.callout-note title="6월 19일: 어떻게 하면 현재 순간에 더 잘 머물 수 있을까?" icon="false"}
<br/>
<br/>
<br/>
:::

::: {.callout-note title="6월 20일: 나는 방에서 침착한 사람인가 아니면 진정시켜야 할 사람인가?" icon="false"}
<br/>
<br/>
<br/>
:::

::: {.callout-note title="6월 21일: 오늘 내 마음을 어떻게 상쾌하게 할 수 있을까?" icon="false"}
<br/>
<br/>
<br/>
:::

::: {.callout-note title="6월 22일: 나는 실제로 내 실패로부터 배우고 있는가?" icon="false"}
<br/>
<br/>
<br/>
:::

::: {.callout-note title="6월 23일: 나는 어디에서 내 길을 막고 있는가?" icon="false"}
<br/>
<br/>
<br/>
:::

::: {.callout-note title="6월 24일: 나는 정말 그렇게 많이 논쟁하고 다툴 필요가 있는가?" icon="false"}
<br/>
<br/>
<br/>
:::

# 26주차: 당신의 길에 있는 것이 길이다

장애물은 삶의 현실입니다. 가장 강력하고 운이 좋은 우리조차도 이 현실에서 예외는 아니지만 우리의 목적 의도 예술적 태도가 어떤 조건에도 적응하여 앞으로 나아갈 길을 찾을 수 있다는 점에서 스토아 철학을 통해 우리 손에 초능력을 가지고 있습니다. 스토아 학파는 이것을 위해 hupexhairesis라는 단어를 사용했는데 이는 필요에 따라 재고하고 새로운 행동 방침을 설정할 수 있도록 하는 일종의 "예비 조항" 또는 "역 조항"으로 행동하는 것을 의미합니다. 마르쿠스 아우렐리우스는 어떤 장애물이든 실제로 새로운 목적을 위한 원료가 될 수 있다고 말합니다! 당신이 직면하고 있는 장애물은 어떻게 새로운 길을 드러낼 수 있을까요?

> "누군가가 우리의 행동을 방해할 수 있다는 것은 사실이지만 그들은 조건적이고 적응력이 있는 힘을 가진 우리의 의도와 태도를 방해할 수 없습니다. 왜냐하면 마음은 그 행동에 대한 어떤 장애물이든 그것을 달성하는 수단으로 적응하고 변환하기 때문입니다. 행동에 대한 장애물인 것이 행동을 진전시키는 것으로 바뀝니다. 길 위의 장애물이 길이 됩니다."
> —마르쿠스 아우렐리우스, 《명상록》, 5.20
> "... 자연이 어떤 장애물이나 반대에도 자신의 목적에 맞게 돌리고 운명적인 질서에 그 자리를 정하고 그것을 채택하는 것처럼, 모든 이성적인 사람은 어떤 장애물이든 자신의 목적을 위한 원료로 변환할 수 있습니다."
> —마르쿠스 아우렐리우스, 《명상록》, 8.35
> "당신은 행동 하나하나를 쌓아 삶을 만들어야 하며 각각이 가능한 한 목표를 달성한다면 만족해야 합니다. 그리고 아무도 당신을 이것으로부터 막을 수 없습니다. 그러나 어떤 외부적인 장애물이 있을 것입니다! 아마도, 그러나 정의, 자제, 지혜로 행동하는 데에는 장애물이 없습니다. 그러나 내 행동의 다른 영역이 좌절된다면 어떻게 될까요? 글쎄요, 장애물을 있는 그대로 기꺼이 받아들이고 당신의 주의를 주어진 것에 돌리십시오. 그러면 다른 행동이 즉시 그 자리를 차지할 것입니다. 당신이 만들고 있는 삶에 더 잘 맞는 행동 말입니다."
> —마르쿠스 아우렐리우스, 《명상록》, 8.32
::: {.callout-note title="6월 25일: 나는 내가 원하는 것뿐만 아니라 가능한 것을 기대하고 있는가?" icon="false"}
<br/>
<br/>
<br/>
:::

::: {.callout-note title="6월 26일: 내가 항상 실패하는 일은 무엇이며 반대로 시도해 본다면 어떨까?" icon="false"}
<br/>
<br/>
<br/>
:::

::: {.callout-note title="6월 27일: 이 역경이 나에게 무엇을 보여줄 수 있을까?" icon="false"}
<br/>
<br/>
<br/>
:::

::: {.callout-note title="6월 28일: 나는 무엇에 대해 자책하는 것을 멈출 수 있을까?" icon="false"}
<br/>
<br/>
<br/>
:::

::: {.callout-note title="6월 29일: 나는 무엇에 대해 변명하는 것을 멈출 수 있을까?" icon="false"}
<br/>
<br/>
<br/>
:::

::: {.callout-note title="6월 30일: 이 장애물을 기회로 어떻게 활용할 수 있을까?" icon="false"}
<br/>
<br/>
<br/>
:::

::: {.callout-note title="7월 1일: 스토아 철학자로서 나의 임무는 무엇인가?" icon="false"}
<br/>
<br/>
<br/>
:::

# 27주차: 자신의 선을 보호하라

에픽테토스의 스승 중 한 명인 무소니우스 루푸스는 인간은 모두 타고난 선함 즉 그가 표현했듯이 미덕에 대한 성향을 가지고 태어난다고 가르쳤습니다. 그 선함이 드러날지 여부를 결정하는 것은 우리의 선택입니다. 우리는 본질적으로 나쁜 사람이 아니지만 때때로 나쁜 일을 할 수도 있습니다. 그렇다면 스토아 철학의 목적은 우리에게 그 선함을 상기시키고 그것을 보호하기 위해 열심히 노력하도록 돕는 것입니다. 이번 주에는 바로 그것을 하기 위해 할 수 있는 선택 즉 취할 수 있는 행동에 대해 글을 쓰는 시간을 보내십시오.

> "당신이 하는 모든 일에서 당신 자신의 선을 보호하고 다른 모든 것에 관해서는 당신이 이성적으로 사용할 수 있는 한 주어진 것을 취하십시오. 만약 당신이 그렇게 하지 않는다면 당신은 불운하고 실패하기 쉽고 방해받고 좌절될 것입니다."
> —에픽테토스, 《담화록》, 4.3.11
> "자신을 깊이 파고들라. 만약 계속 파고든다면 언제나 흐를 준비가 된 선의 샘이 있기 때문이다."
> —마르쿠스 아우렐리우스, 《명상록》, 7.59
::: {.callout-note title="7월 2일: 내가 피하고 있는 더 어려운 선택은 무엇인가?" icon="false"}
<br/>
<br/>
<br/>
:::

::: {.callout-note title="7월 3일: 의무 대신 기회를 본다면 어떨까?" icon="false"}
<br/>
<br/>
<br/>
:::

::: {.callout-note title="7월 4일: 나는 미덕의 불꽃을 계속 타오르게 하고 있는가?" icon="false"}
<br/>
<br/>
<br/>
:::

::: {.callout-note title="7월 7일: 오디세우스와 같은 결단력과 인내심을 보여줄 수 있을까?" icon="false"}
<br/>
<br/>
<br/>
:::

::: {.callout-note title="7월 8일: 어떤 고통스러운 일에 대해 책임을 질 수 있을까?" icon="false"}
<br/>
<br/>
<br/>
:::

# 28주차: 세 번째 것을 찾지 마세요

스토아 학파는 우리에게 선행은 그 자체로 보상이라고 가르칩니다. 옳은 일을 하고 누군가가 그것으로 도움을 받는 것을 보는 것만으로도 충분합니다. 그 위에 감사 인사를 기대하는 것 즉 마르쿠스 아우렐리우스가 "세 번째 것"이라고 묘사한 것을 기대하는 것은 탐욕스러운 것입니다. 점수를 매기는 것은 선행의 목적을 놓칠 뿐만 아니라 어리석은 짓입니다. 그것은 당신을 실망하게 만듭니다. 만약 당신이 회계를 할 것이라면 다른 방향에서 그것을 보십시오. 얼마나 많은 사람들이 우리를 도왔으며 우리는 그들에게 무엇을 빚지고 있습니까? 이번 주에는 당신의 빚을 청산하는 것에 대해 생각하고 다른 사람들이 당신에게 빚지고 있다는 생각을 용서하는 것을 고려하십시오.

> "한 사람은 다른 사람에게 선을 행하자마자 즉시 보답으로 기대되는 호의를 계산합니다. 다른 사람은 그렇게 빠르지는 않지만 여전히 그 사람을 채무자로 여기고 호의를 압니다. 세 번째 종류의 사람은 마치 포도 덩굴이 더 이상 요구하지 않고 포도송이를 생산하는 것처럼, 그 행위를 의식하지 않는 것처럼 행동합니다. 경주 후의 말이나 산책 후의 개 또는 꿀을 만든 후의 벌처럼 말입니다. 그러한 사람은 선행을 한 후에 옥상에서 소리치지 않고 단지 다음 행위로 넘어갑니다. 마치 포도 덩굴이 적절한 계절에 또 다른 포도송이를 생산하는 것처럼 말입니다."
> —마르쿠스 아우렐리우스, 《명상록》, 5.6
> "당신이 잘했고 다른 사람이 그것으로 이익을 얻었을 때 왜 바보처럼 그 위에 세 번째 것, 즉 선행에 대한 공로나 보답을 찾는가?"
> —마르쿠스 아우렐리우스, 《명상록》, 7.73
::: {.callout-note title="7월 9일: 나는 철학자의 길을 가고 있는가 아니면 즉흥적으로 하고 있는가?" icon="false"}
<br/>
<br/>
<br/>
:::

::: {.callout-note title="7월 10일: 나는 내 기술에 헌신하고 있는가?" icon="false"}
<br/>
<br/>
<br/>
:::

::: {.callout-note title="7월 11일: 오늘 나는 어떻게 나 자신을 향상시킬 것인가?" icon="false"}
<br/>
<br/>
<br/>
:::

::: {.callout-note title="7월 12일: 어떤 원칙이 내 행동을 지배하는가?" icon="false"}
<br/>
<br/>
<br/>
:::

::: {.callout-note title="7월 13일: 나는 지도자가 될 준비가 되었는가? 내 일을 할 준비가 되었는가?" icon="false"}
<br/>
<br/>
<br/>
:::

::: {.callout-note title="7월 14일: 나는 더 겸손해지고 있는가 아니면 덜 겸손해지고 있는가?" icon="false"}
<br/>
<br/>
<br/>
:::

::: {.callout-note title="7월 15일: 보상의 약속 없이도 옳은 일을 할 수 있을까?" icon="false"}
<br/>
<br/>
<br/>
:::

# 29주차: 분노 대신 온유함을 실천하라

마르쿠스 아우렐리우스가 화를 내는 것을 상상하기 쉽습니다. 그의 책임은 방대했고 그의 직업은 많은 좌절스럽고 어려운 사람들과 함께 일해야 했습니다. 따라서 그는 분노 문제에 대해 예리한 감각을 가지고 있었고 그것이 얼마나 비생산적일 수 있는지 그리고 그것이 사용자를 얼마나 비참하게 만들 수 있는지 알고 있었습니다. 그는 종종 분노를 온유함으로 대체함으로써 다른 사람들에 대한 선의를 보존하도록 고안된 간단한 수련을 반복했습니다. 우리는 우리 자신을 선의에서 버리도록 허용할 수 없으며 아무도 기꺼이 실수를 저지르지 않는다는 것을 스스로에게 상기시켜야 합니다. 이번 주에 분노를 느낄 때마다 마르쿠스를 기억하고 그것을 온유함으로 어떻게 대체할 수 있는지 확인하고 이러한 예를 기록하십시오.

> "이성의 길을 따라 앞으로 나아가면서 사람들이 당신의 길을 막을 것입니다. 그들은 결코 당신이 건전한 일을 하는 것을 막을 수 없을 것이므로 그들이 당신에 대한 당신의 선의를 꺾게 하지 마십시오. 두 전선 모두에서 꾸준히 경계하십시오. 잘 근거 있는 판단과 행동뿐만 아니라 우리의 길을 방해하거나 다른 어려움을 만드는 사람들에 대한 온유함도 마찬가지입니다. 왜냐하면 화를 내는 것도 약점이며 과제를 포기하거나 공황 상태에서 항복하는 것과 마찬가지이기 때문입니다."
> —마르쿠스 아우렐리우스, 《명상록》, 11.9
> "플라톤이 말했듯이 모든 영혼은 그 의지에 반하여 진리로부터 박탈당합니다. 정의, 자제, 타인에 대한 선의, 그리고 모든 유사한 미덕에 대해서도 마찬가지입니다. 이것을 끊임없이 마음에 새기는 것이 필수적입니다. 왜냐하면 그것은 당신을 모든 사람에게 더 온유하게 만들 것이기 때문입니다."
> —마르쿠스 아우렐리우스, 《명상록》, 7.63
> "분노가 치밀어 오를 때 이 생각을 염두에 두십시오. 분노하는 것은 남자답지 않습니다. 오히려 온유함과 예의 바름이 더 인간적이고 따라서 더 남자답습니다. 진정한 남자는 분노와 불만에 굴복하지 않으며 그러한 사람은 힘, 용기, 인내를 가지고 있습니다..."
> —마르쿠스 아우렐리우스, 《명상록》, 11.18.5B
::: {.callout-note title="7월 16일: 나는 어떤 봉사에 헌신하고 있는가?" icon="false"}
<br/>
<br/>
<br/>
:::

::: {.callout-note title="7월 17일: 나는 어디에서 다른 사람들을 버렸는가?" icon="false"}
<br/>
<br/>
<br/>
:::

::: {.callout-note title="7월 18일: 나는 내 일에만 신경 쓰고 다른 사람들에게 방해받지 않을 수 있을까?" icon="false"}
<br/>
<br/>
<br/>
:::

::: {.callout-note title="7월 19일: 용서는 어떤 느낌일까?" icon="false"}
<br/>
<br/>
<br/>
:::

::: {.callout-note title="7월 20일: 나는 정의로운 삶을 살고 있는가?" icon="false"}
<br/>
<br/>
<br/>
:::

::: {.callout-note title="7월 21일: 어떻게 하면 다른 사람들과 더 잘 협력할 수 있을까?" icon="false"}
<br/>
<br/>
<br/>
:::

::: {.callout-note title="7월 22일: 나는 고귀하게 행동하고 있는가 아니면 마지못해 행동하고 있는가?" icon="false"}
<br/>
<br/>
<br/>
:::

# 30주차: "뉴스"를 통제하기

고대인들조차도 가십과 뉴스에 압도당한다고 느꼈습니다. 이번 주 LL은 문자 전화 이메일부터 24/7 뉴스 기계의 끊임없는 갈기갈기까지 그들이 상상할 수 없었던 공세에 직면하게 될 것입니다. 모든 상태 업데이트 긴급 전화 또는 최신 유행하는 선동적인 뉴스 기사에 응답하는 대신 스토아 학파가 현재 순간의 목적과 의무에 집중하기 위해 사용했던 세 가지 방법을 기억하는 시간을 가지십시오. (1) 소음에서 벗어나십시오. (2) 어떤 뉴스도 현재 선택의 목적에서 당신을 벗어나게 할 수 없다는 것을 기억하십시오. (3) 보도되는 내용에 부정적인 (또는 긍정적인) 것을 추가하지 마십시오.

> "속보에 정신이 팔렸습니까? 그렇다면 여가 시간을 내어 좋은 것을 배우고 이리저리 튀는 것을 멈추십시오. 그러나 그렇게 할 때 다른 실수를 명심하십시오. 즉 통제력을 얻는 데 너무 정신이 팔려서 지쳐버리고 충동과 생각을 지시할 수 있는 목적을 잃하게 되는 것입니다."
> —마르쿠스 아우렐리우스, 《명상록》, 2.7
> "불안한 소식이 전달될 때마다 어떤 소식도 당신의 이성적인 선택과 관련이 있을 수 없다는 것을 명심하십시오. 누군가 당신의 가정이나 욕망이 틀렸다는 소식을 전할 수 있습니까? 절대 아닙니다! 그러나 그들은 누군가 죽었다고 말할 수 있습니다. 그렇다 하더라도 그것이 당신에게 무슨 상관입니까?"
> — 에픽테토스, 《담화록》, 3.18.1-2
> "초기 인상이 보고하는 것 이상으로 자신에게 아무것도 말하지 마십시오. 누군가 당신에 대해 나쁘게 말하고 있다는 보고를 받았습니다. 이것이 보고입니다. 당신이 해를 입었다는 보고는 아니었습니다. 내 아들이 아프다는 것을 봅니다. 그러나 그의 생명이 위험하다는 것은 아닙니다. 그러므로 항상 첫인상 안에 머물고 머릿속에서 그것들에 추가하지 마십시오. 이렇게 하면 당신에게 아무 일도 일어날 수 없습니다."
> —마르쿠스 아우렐리우스, 《명상록》, 8.49
::: {.callout-note title="7월 23일: 좋든 나쁘든 그 어떤 것도 내 머릿속에 들어가지 않도록 어떻게 할 수 있을까?" icon="false"}
<br/>
<br/>
<br/>
:::

::: {.callout-note title="7월 24일: 불안한 소식을 받을 때 침착함을 유지할 수 있을까?" icon="false"}
<br/>
<br/>
<br/>
:::

::: {.callout-note title="7월 25일: 나는 어디에서 일이 내 삶의 질을 떨어뜨리게 하는가?" icon="false"}
<br/>
<br/>
<br/>
:::

::: {.callout-note title="7월 26일: 어디에 내가 도울 수 있을까? 어떻게 도울 수 있을까?" icon="false"}
<br/>
<br/>
<br/>
:::

::: {.callout-note title="7월 27일: 미덕보다 나은 것은 무엇인가?" icon="false"}
<br/>
<br/>
<br/>
:::

::: {.callout-note title="7월 28일: 나는 어디에서 특권을 누렸으며 그것으로 무엇을 하고 있는가?" icon="false"}
<br/>
<br/>
<br/>
:::

::: {.callout-note title="7월 29일: 어디에서 자신감을 찾을 수 있을까?" icon="false"}
<br/>
<br/>
<br/>
:::

# 31주차: 불평 없는 한 주

에픽테토스는 학생들에게 비난과 불평을 포기해야 할 필요성에 대해 자주 이야기했습니다. 사실 그는 그것을 삶의 기술에서 진보를 측정하는 주요 척도 중 하나로 보았습니다. 손가락질하는 데 얼마나 많은 삶이 낭비됩니까? 불평이 단 하나의 문제를 해결한 적이 있습니까? 마르쿠스 아우렐리우스는 "자신을 탓하거나 아무도 탓하지 말라"고 말했을 것입니다. 이번 주에는 불평 대신 건설적인 피드백을 비난 대신 책임을 시도하십시오. 그리고 무언가 잘못되면 진정한 원인이 무엇이었는지 성찰하는 시간을 보내십시오. 이 일기장에서든 소리 내어든 불평으로 단 1분도 낭비하지 마십시오.

> "당신은 신을 비난하는 것을 멈춰야 하고 어떤 사람도 비난해서는 안 됩니다. 당신은 당신의 욕망을 완전히 통제하고 당신의 회피를 당신의 이성적인 선택 안에 있는 것으로 옮겨야 합니다. 당신은 더 이상 분노 원한 시기 또는 후회를 느껴서는 안 됩니다."
>
> -에픽테토스, 《담화록》, 3.22.13

> "왜냐하면 내 이성적인 선택 밖의 어떤 것도 그것을 방해하거나 해칠 수 없기 때문입니다. 내 이성적인 선택만이 스스로에게 이것을 할 수 있습니다. 만약 우리가 실패할 때마다 이런 식으로 기울고 오직 우리 자신만을 탓하고 오직 의견만이 혼란스러운 마음과 불안의 원인이라는 것을 기억한다면 신에 의해 나는 우리가 진보하고 있을 것이라고 맹세합니다."
>
> -에픽테토스, 《담화록》, 3.19.2-3

> "그러나 만약 당신이 당신의 것만을 당신의 것으로 여기고 다른 사람에게 속한 것을 진정으로 당신의 것이 아니라고 여긴다면 아무도 당신을 강요하거나 막을 수 없을 것이며 당신은 비난하거나 고발할 사람을 찾지 못할 것이며 당신은 당신의 의지에 반하는 어떤 것도 하지 않을 것이며 당신은 적이 없을 것이며 아무도 당신에게 해를 끼치지 않을 것입니다. 왜냐하면 어떤 해도 당신에게 영향을 미칠 수 없기 때문입니다."
>
> -에픽테토스, 《엔키리디온》, 1.3

::: {.callout-note title="7월 30일: 오늘 나는 목적 탁월함 의무에서 기쁨을 찾을 수 있을까?" icon="false"}
<br/>
<br/>
<br/>
:::

::: {.callout-note title="7월 31일: 나는 전문가를 위해 개인적인 것을 소홀히 하고 있는가?" icon="false"}
<br/>
<br/>
<br/>
:::

::: {.callout-note title="8월 1일: 나의 이상주의는 어디에서 나를 방해하는가?" icon="false"}
<br/>
<br/>
<br/>
:::

::: {.callout-note title="8월 3일: 바로 지금 여기에서 최대한의 것을 얻을 수 있을까?" icon="false"}
<br/>
<br/>
<br/>
:::

::: {.callout-note title="8월 4일: 오늘 나는 어떻게 무익한 감정을 피할 수 있을까?" icon="false"}
<br/>
<br/>
<br/>
:::

::: {.callout-note title="8월 5일: 오늘 나는 입을 다물 수 있을까?" icon="false"}
<br/>
<br/>
<br/>
:::

# 32주차: 어떤 작은 승리를 찾을 수 있을까요?

키티온의 제논, 난파 후 아고라의 채색된 현관(stoa poikilē)에 스토아 학파를 세운 페니키아 상인은 행복이 작은 발걸음의 문제라고 말했습니다. 스토아 학파는 인간의 완벽성을 믿었지만 그 잠재력을 실현하는 데 많은 장애물이 있다는 것을 알았습니다. 그래서 그들은 오늘날 우리 문화가 집착하는 소위 서사적 승리와 양자 도약에 회의적이었을 것입니다. 대신 그들은 당신이 매일의 의무에 집중하고 점진적인 진전을 이루도록 촉구했을 것입니다. 이번 주에는 당신이 쌓을 수 있는 작은 승리 이 개선이나 저 개선 여기에서의 결정이나 저기에서의 결정에서 얻을 수 있는 작은 이득에 대해 생각하며 글쓰기 시간을 보내십시오. 각 작은 발걸음에 만족하십시오. 계속 움직이고 포기하지 마십시오.

> "마지못해 이기적으로 부주의하게 또는 반대 의견을 내기 위해 행동하지 마십시오. 당신의 생각을 멋진 언어로 과장하지 마십시오. 너무 많은 말과 너무 많은 행동을 하는 사람이 되지 마십시오.... 쾌활하고 외부의 도움이나 다른 사람이 가져다 줄 수 있는 안도를 원하지 마십시오. 사람은 스스로 서야 하며 지탱되어서는 안 됩니다."
> —마르쿠스 아우렐리우스, 《명상록》, 3.5
> "우리는 그것들을 완벽하게 할 수 있다는 절망 때문에 우리의 추구를 포기하지 않습니다."
>
> -- 에픽테토스, 《담화록》, 1.2.37B

> "말하기보다 듣는 편이 낫습니다."
> —제논 (디오게네스 라에르티우스가 인용한 바에 따름), 《저명한 철학자들의 생애》, 7.1.26 (의역)

::: {.callout-note title="8월 6일: 오늘 나는 어떤 작은 진전을 이룰 수 있을까?" icon="false"}
<br/>
<br/>
<br/>
:::

::: {.callout-note title="8월 7일: 환경이 아무리 힘들어도 잘 살 수 있을까?" icon="false"}
<br/>
<br/>
<br/>
:::

::: {.callout-note title="8월 8일: 오늘 큰 일을 향한 가장 작은 발걸음은 무엇일까?" icon="false"}
<br/>
<br/>
<br/>
:::

::: {.callout-note title="8월 11일: 내 습관이 나아지고 있는가?" icon="false"}
<br/>
<br/>
<br/>
:::

::: {.callout-note title="8월 12일: 나는 이 철학을 실천에 옮김으로써 내 것으로 만들고 있는가?" icon="false"}
<br/>
<br/>
<br/>
:::

# 33주차: 항상 자신에게 이 질문을 하십시오

우리가 일주일 동안 하는 말과 행동의 대부분은 전혀 불필요합니다. 회의 물질적 소유 대립 추구 - 무의미한 방해와 문제입니다. 그것들은 우리를 평온과 목적에서 멀어지게 합니다. 스토아 철학자는 이러한 유혹과 의무를 이 질문 즉 이번 주에 일기를 쓰는 데 앞장서야 할 질문을 함으로써 극복합니다. 시도해 보십시오. 말하거나 행동하거나 무언가를 사기 전에 간단히 물어보십시오. "이것은 필요한 것들 중 하나인가?"

> "마음의 평화를 원한다면 작은 일에 몰두하라고 합니다. 그러나 더 나은 말은 '공공 생활을 위해 창조된 이성적인 존재로서 해야 할 일을 하고 필요한 대로 하라'가 아닐까요? 이것은 적은 일을 하는 마음의 평화뿐만 아니라 그것들을 잘 하는 더 큰 평화를 가져다주기 때문입니다. 우리의 말과 행동의 대부분은 불필요하므로 그것들을 통제하면 여가와 평온이 풍부해질 것입니다. 결과적으로 우리는 매 순간 '이것은 불필요한 것들 중 하나인가?'라고 묻는 것을 잊지 말아야 합니다. 그러나 우리는 불필요한 행동뿐만 아니라 불필요한 생각도 통제해야 합니다. 그래야 불필요한 행동이 그 뒤를 따르지 않을 것입니다."
>
> -마르쿠스 아우렐리우스, 《명상록》, 4.24

> "당신이 하는 모든 일에서 당신의 의무를 다하고 결과에 상관없이 그것을 기쁘게 여기십시오. 당신의 선한 행동 그 자체가 당신의 보상이기 때문입니다."
> —세네카, 《도덕 서한》, 81.19 (의역)
::: {.callout-note title="8월 13일: 어떤 문제를 미리 해결할 수 있을까?" icon="false"}
<br/>
<br/>
<br/>
:::

::: {.callout-note title="8월 14일: 오늘 철학이 내 진로를 어떻게 이끌어 줄까?" icon="false"}
<br/>
<br/>
<br/>
:::

::: {.callout-note title="8월 15일: 오늘 내가 내리는 결정은 진정한 판단에 근거할 것인가?" icon="false"}
<br/>
<br/>
<br/>
:::

::: {.callout-note title="8월 16일: 오늘의 역경을 어떻게 장점으로 바꿀 것인가?" icon="false"}
<br/>
<br/>
<br/>
:::

::: {.callout-note title="8월 17일: 하루 종일 다른 사람을 탓하지 않고 지낼 수 있을까?" icon="false"}
<br/>
<br/>
<br/>
:::

::: {.callout-note title="8월 18일: 어디에서 내 강점을 더 잘 발휘할 수 있을까?" icon="false"}
<br/>
<br/>
<br/>
:::

::: {.callout-note title="8월 19일: 내 삶에서 어떤 불필요한 것들을 없앨 수 있을까?" icon="false"}
<br/>
<br/>
<br/>
:::

# 34주차: 미래의 불행에 '아니오'라고 말하세요

나는 우리가 얼마나 자주 미리 자신을 비참하게 만드는지 모릅니다. 이것에 대한 두려움 때문에 저것에 대한 절망적인 희망 때문에. 우리가 특정 미래를 갈망하거나 피하는 데 집중할 때 우리는 현재 여기에서 자신을 비참하게 만듭니다. 위대한 중기 스토아 학자 파나이티우스의 위대한 제자인 로도스의 헤카토는 이 비참함이 항상 우리가 상상하는 미래 결과에 부여하는 희망이나 두려움과 관련이 있다고 가르쳤습니다. 이것으로부터 세네카는 이번 주에 둘 다에게 '아니오'라고 말하라고 상기시킵니다. 왜냐하면 그것들에 빠지는 것은 현재를 즐길 수 있는 능력을 우리에게서 빼앗기 때문입니다. 글을 쓸 때 미래에 대해 생각하지 마십시오. 당신이 일어나기를 바라는 것 당신이 두려워하는 것 바로 지금에 집중하십시오. 당신이 지금 하고 있고 생각하고 있는 것.

> "감사하는 마음은 가장 큰 미덕입니다."
> —세네카, 《도덕 서한》, 73.15 (의역)

> "그러나 우리가 두려움이 우세하게 놔둔다면 살 이유도 없고 우리의 비참함에 한계도 없다."
>
> -세네카, 《도덕 서한》, 13.12B

> "헤카토는 '희망을 버리면 두려움도 버리게 될 것이다'라고 말합니다... 이 두 가지 병의 주된 원인은 우리가 현재 상황에 적응하는 대신 생각을 너무 멀리 보내기 때문입니다."
>
> -- 세네카, 《도덕 서한》, 5.7B-8

::: {.callout-note title="8월 20일: 내 영혼은 얼마나 잘 차려입었는가?" icon="false"}
<br/>
<br/>
<br/>
:::

::: {.callout-note title="8월 21일: 미래에 대한 걱정을 멈추고 현재를 즐긴다면 어떨까?" icon="false"}
<br/>
<br/>
<br/>
:::

::: {.callout-note title="8월 22일: 어떤 사소한 일에 신경 쓰는 것을 멈출 수 있을까?" icon="false"}
<br/>
<br/>
<br/>
:::

::: {.callout-note title="8월 23일: 나는 어디에서 좋은 것을 너무 많이 가지고 있는가?" icon="false"}
<br/>
<br/>
<br/>
:::

::: {.callout-note title="8월 24일: 다른 사람들 심지어 내가 좋아하지 않는 사람들에게서도 무엇을 배울 수 있을까?" icon="false"}
<br/>
<br/>
<br/>
:::

::: {.callout-note title="8월 25일: 오늘 나는 어떤 새로운 길을 개척할 수 있을까?" icon="false"}
<br/>
<br/>
<br/>
:::

# 35주차: 미루는 버릇을 고치는 약

스토아 철학자에게 미루는 것은 거의 망상과 특권 의식의 한 형태로 보입니다. 다음 달이나 다음 주에 그것을 처리할 수 있을 것이라고 누가 말할 수 있습니까? 만약 그것이 중요하다면 그들은 기다리지 말라고 말할 것입니다. 지금 하십시오. 마르쿠스가 말했듯이 만약 그것이 행해져야 한다면 "용기"와 신속함으로 하십시오. 미루는 것은 일을 더 쉽게 만드는 것처럼 보이지만 우리를 낮은 수준의 갉아먹는 불안 상태로 저주합니다. 이번 주를 그렇게 보내고 싶습니까? 어느 주든? 마지막 주? 자신에게 물어보십시오. 나는 무엇을 피하고 있는가? 내일 대신 오늘 처리할 수 있는 것은 무엇인가? 지금 당장 신속하고 용감하게 할 수 있는 것은 무엇인가?

> "노인이나 노년에 가까운 사람이 공책에 담긴 지식만 가지고 있는 것은 부끄러운 일입니다. 제논은 이렇게 말했습니다... 당신은 뭐라고 말합니까? 클레안테스는 저렇게 말했습니다... 당신은 뭐라고 말합니까? 얼마나 오랫동안 다른 사람의 주장에 의해 강요당할 것입니까? 책임을 지고 자신의 주장을 펼치십시오. 후세가 공책에 담을 무언가를 말입니다."
> —세네카, 《도덕 서한》, 33.7B
> "이것이 성격의 완벽함의 표시입니다. 매일을 마지막 날인 것처럼 보내되 광란 게으름 또는 어떤 가식도 없이 보내는 것입니다."
>
> -마르쿠스 아우렐리우스, 《명상록》, 7.69

> "좋은 사람이 되는 것은 당신의 손에 달려 있습니다."
> —마르쿠스 아우렐리우스, 《명상록》, 8.1 (의역)
::: {.callout-note title="8월 27일: 우는 것보다 웃는 법을 어디에서 배울 수 있을까?" icon="false"}
<br/>
<br/>
<br/>
:::

::: {.callout-note title="8월 28일: 어떤 사치품을 필요로 하지 않는 연습을 할 수 있을까?" icon="false"}
<br/>
<br/>
<br/>
:::

::: {.callout-note title="8월 29일: 오늘 나는 어떤 욕구를 없앨 수 있을까?" icon="false"}
<br/>
<br/>
<br/>
:::

::: {.callout-note title="8월 30일: 오늘의 의무를 용기와 자신감을 가지고 수행할 수 있을까?" icon="false"}
<br/>
<br/>
<br/>
:::

::: {.callout-note title="8월 31일: 나는 어디에서 다른 사람들에게 잘못을 저질렀는가?" icon="false"}
<br/>
<br/>
<br/>
:::

::: {.callout-note title="9월 1일: 나는 내 영혼을 어떤 운명보다 강하게 만들기 위해 노력하고 있는가?" icon="false"}
<br/>
<br/>
<br/>
:::

# 36주차: 혹독한 겨울 훈련

삶의 기술에는 세 가지 수준의 훈련이 있습니다. 즉 공부 실천 그리고 혹독한 훈련입니다. 스토아 학파를 읽는 것은 공부입니다. 이 저널에서 교훈을 시험하고 성찰하는 것은 실천입니다. 남은 것은 혹독한 훈련입니다. 에픽테토스는 로마 군대가 겨울의 비수기에 혹독하게 훈련하여 봄에 전투에 복귀했을 때 어떤 도전에도 대비할 수 있도록 하는 비유를 사용하는 것을 좋아했습니다. 세네카는 매달 평소보다 더 힘든 조건에 자신을 노출시키는 시간을 보냈습니다. 그 역시 군사적 비유를 사용하여 적이 결국 올 때 강해지도록 군인들이 힘든 일을 맡는 방식을 지적했습니다. 이번 주에는 단순한 공부와 실천을 넘어 자신을 밀어붙이기 위해 무엇을 하고 있습니까?

> "우리는 혹독한 겨울 훈련을 거쳐야 하며 준비되지 않은 일에 서두르지 말아야 합니다."
>
> -에픽테토스, 《담화록》, 1.2.32

> "당신의 마음의 기개를 시험할 교훈이 여기 있습니다. 일주일 중 일부를 가장 빈약하고 값싼 음식만 먹고 초라한 옷을 드물게 입고 이것이 정말 당신이 두려워했던 최악의 상황인지 자문해 보십시오. 좋은 시절에 더 힘든 시절을 대비해야 합니다. 왜냐하면 행운이 친절할 때 영혼은 그녀의 파괴에 대한 방어책을 세울 수 있기 때문입니다. 그래서 군인들은 평화 시에 기동 훈련을 하고 적이 보이지 않는 곳에 벙커를 세우고 공격을 받지 않고 지쳐서 공격이 올 때 지치지 않도록 합니다."
>
> -세네카, 《도덕 서한》, 18.5-6

> "도전이 당신을 마주할 때 신이 당신을 신체 트레이너처럼 더 젊은 스파링 파트너와 맞붙이고 있다는 것을 기억하십시오. 왜? 올림픽 선수가 되려면 땀이 필요합니다! 나는 당신이 그 더 젊은 스파링 파트너처럼 그것을 사용한다면 당신보다 더 나은 도전을 가진 사람은 아무도 없다고 생각합니다."
>
> -에픽테토스, 《담화록》, 1.24.1-2

::: {.callout-note title="9월 3일: 나는 다가올 일을 위해 비수기에 어떻게 준비하고 있는가?" icon="false"}
<br/>
<br/>
<br/>
:::

::: {.callout-note title="9월 4일: 이 어려움들을 교훈과 시험으로 어떻게 볼 수 있을까?" icon="false"}
<br/>
<br/>
<br/>
:::

::: {.callout-note title="9월 5일: 진정으로 내 것은 무엇인가?" icon="false"}
<br/>
<br/>
<br/>
:::

::: {.callout-note title="9월 6일: 만약 내가 자유를 잃는다면 그것이 나를 무너뜨릴까?" icon="false"}
<br/>
<br/>
<br/>
:::

::: {.callout-note title="9월 7일: 오늘 나는 선택의 힘을 어떻게 사용할 것인가?" icon="false"}
<br/>
<br/>
<br/>
:::

::: {.callout-note title="9월 8일: 내 거품이 터질 준비가 되었는가?" icon="false"}
<br/>
<br/>
<br/>
:::

::: {.callout-note title="9월 9일: 나는 내 두려움을 지배하는가 아니면 두려움이 나를 지배하는가?" icon="false"}
<br/>
<br/>
<br/>
:::

# 37주차: 기도하는 새로운 방법

우리는 종종 우리가 바라는 것들을 위해 기도하고 그 과정에서 우리 자신을 방정식에서 제외시킵니다. 우리는 하늘이 마법처럼 우리가 원하는 결과를 선물해 주기를 바라고 있습니다. 그것이 승진이든 사랑하는 사람의 빠른 회복이든 말입니다. 스토아 학파는 당신에게 이것을 멈추라고 촉구할 것입니다. 마르쿠스 아우렐리우스는 신들에게 쾌락이나 안락에 대한 요구 목록을 제시하지 말고 대신 그러한 것들이 필요하지 않도록 도와달라고 요청하라고 스스로에게 상기시켰습니다. 어떤 의미에서 그는 정말로 내면의 힘을 구하고 있었던 것입니다. 그는 자신에게 묻고 있었습니다. 이번 주에 당신이 원하고 기도하거나 바라는 모든 것들에 대해 생각하고 그것들을 그렇게 뒤집어 보십시오. 대신 무엇을 생각해 내는지 보십시오.

> "다르게 기도해 보고 무슨 일이 일어나는지 보십시오. '그녀와 잘 수 있는 방법'을 구하는 대신 '그녀와 자고 싶은 욕망을 멈추는 방법'을 구하십시오. '그를 없애는 방법' 대신 '그의 죽음을 갈망하지 않는 방법'을 구하십시오. '내 아이를 잃지 않는 방법' 대신 '그것에 대한 두려움을 잃는 방법'을 구하십시오."
>
> -마르쿠스 아우렐리우스, 《명상록》, 9.40.(6)

> "우리는 전능하신 하나님께 부르짖습니다. 어떻게 이 고통에서 벗어날 수 있습니까? 바보야, 손이 없느냐? 아니면 하나님이 한 쌍을 주는 것을 잊으셨을까? 앉아서 코가 흐르지 않기를 기도하라! 아니면 그냥 코를 닦고 희생양을 찾는 것을 멈춰라."
>
> -에픽테토스, 《담화록》, 2.16.13

> "그러나 나는 내 의지에 방해를 받거나 강요당한 적이 한 번도 없습니다. 그리고 이것이 어떻게 가능합니까? 나는 내 행동의 선택을 신의 의지와 결부시켰습니다. 신은 내가 아프기를 원하시니 그것이 내 의지입니다. 그는 내가 무언가를 선택하기를 원하시니 나도 그렇게 합니다. 그는 내가 무언가에 손을 뻗거나 무언가가 나에게 주어지기를 원하시니 나도 같은 것을 원합니다. 신이 원하지 않는 것은 나는 원하지 않습니다."
>
> -- 에픽테토스, 《담화록》, 4.1.89

::: {.callout-note title="9월 10일: 내가 두려워하는 상실에 어떻게 대비할 수 있을까?" icon="false"}
<br/>
<br/>
<br/>
:::

::: {.callout-note title="9월 11일: 오늘 나는 어디에서 덜 써도 될까?" icon="false"}
<br/>
<br/>
<br/>
:::

::: {.callout-note title="9월 12일: 나는 어디에서 허세를 부리고 있는가?" icon="false"}
<br/>
<br/>
<br/>
:::

::: {.callout-note title="9월 13일: 내 내면의 성채는 얼마나 강한가?" icon="false"}
<br/>
<br/>
<br/>
:::

::: {.callout-note title="9월 14일: 당신은 기도하고 있는가 아니면 요구하고 있는가?" icon="false"}
<br/>
<br/>
<br/>
:::

::: {.callout-note title="9월 15일: 당신은 지글지글인가 아니면 스테이크인가?" icon="false"}
<br/>
<br/>
<br/>
:::

::: {.callout-note title="9월 16일: 나는 오늘의 재앙과 공황을 이겨낼 것인가?" icon="false"}
<br/>
<br/>
<br/>
:::

# 38주차: 싫어하는 사람 다루기

스토아 학파는 친절이 증오를 이긴다고 가르쳤습니다. 그들은 증오에 참여하는 사람들이 의도된 대상이 아니라 실천자를 해치는 파괴적인 열정의 죄수라고 믿었습니다. 증오하는 사람을 미워할 이유가 없습니다. 그들은 이미 충분히 고통받고 있습니다. 사실 당신이 그들을 이런 식으로 볼 때 친절하고 선량하고 진실하고 유용하게 대하기가 더 쉬워집니다. 성경에서 원수를 사랑하는 것이 그들에게 뜨거운 석탄을 붓는 것과 같다는 구절을 기억하십니까? 왜냐하면 그것은 너무나 예상치 못한 일이기 때문입니다. 이번 주에 누구를 그렇게 놀라게 할 수 있습니까? 누구의 적의를 친절과 연민으로 만날 수 있습니까? 그렇게 함으로써 얼마나 기분이 좋아집니까?

> "누군가 나를 경멸한다면 어떨까? 그들이 알아서 하게 놔두라. 그러나 나는 경멸받을 만한 행동이나 말을 하지 않도록 할 것이다. 누군가 나를 미워한다면 어떨까? 그들이 알아서 하게 놔두라. 그러나 나는 모든 사람에게 친절하고 선량하며 심지어 미워하는 사람에게도 그들이 어디서 잘못했는지 보여줄 준비가 되어 있을 것이다. 비판적인 방식이나 내 인내심을 과시하기 위해서가 아니라 진정으로 그리고 유용하게."
>
> -마르쿠스 아우렐리우스, 《명상록》, 11.13

> "친절은 무적이지만 위선이나 가식이 없는 진실할 때만 그렇습니다. 당신이 계속 친절을 보이고 기회가 주어진다면 그들이 당신에게 해를 끼치려고 할 때 바로 그들이 어디서 잘못했는지 부드럽게 지적한다면 가장 악의적인 사람이라도 무엇을 할 수 있겠습니까?"
>
> -마르쿠스 아우렐리우스, 《명상록》, 11.18.5.9A

> "당신에게 악의를 품고 당신을 공격하는 사람이 당신에게 해를 끼치는 것이 아니라 오히려 학대에 대한 당신 자신의 믿음에서 해가 온다는 것을 명심하십시오. 그러므로 누군가 당신의 분노를 불러일으킬 때 그것을 부채질하는 것은 정말로 당신 자신의 의견이라는 것을 아십시오. 대신 그러한 인상에 휩쓸리지 않는 것을 첫 번째 반응으로 삼으십시오. 왜냐하면 시간과 거리를 두면 자제력이 더 쉽게 달성되기 때문입니다."
>
> -에픽테토스, 《엔키리디온》, 20

::: {.callout-note title="9월 19일: 나는 내 마음을 바꾸고 피드백을 받아들일 만큼 유연한가?" icon="false"}
<br/>
<br/>
<br/>
:::

::: {.callout-note title="9월 20일: 예상치 못한 공격에 얼마나 준비가 되어 있는가?" icon="false"}
<br/>
<br/>
<br/>
:::

::: {.callout-note title="9월 21일: 어떤 방해가 있더라도 삶의 리듬을 유지할 수 있을까?" icon="false"}
<br/>
<br/>
<br/>
:::

::: {.callout-note title="9월 22일: 오늘의 어려움이 내 성격을 어떻게 보여줄까?" icon="false"}
<br/>
<br/>
<br/>
:::

::: {.callout-note title="9월 23일: 내 훈련은 어떻게 되어가고 있는가?" icon="false"}
<br/>
<br/>
<br/>
:::

# 39주차: 공황은 자해다

공황 상태로 개선되는 상황을 하나만 들어보세요. 만약 있다면 적어보세요! 세네카는 그의 편지와 에세이에서 공황 문제에 대해 자주 숙고했습니다. 그것은 위험을 만들고 효과적으로 기능하는 우리의 능력을 제한합니다. 그것은 우리가 성공을 찾고 객관적으로 보는 것을 막습니다. 더 나쁜 것은 우리가 그렇게 걱정하는 위험에 진정으로 직면한 적이 없기 때문에 시간이 지남에 따라 우리를 더 약하게 만듭니다. 당신을 공황 상태에 빠뜨릴 수 있는 무서운 것들에 대해 명상하십시오. 그것들에 대해 무엇이 그렇게 압도적인지 생각해 보십시오. 그것들을 이해하게 되십시오. 그것들과 친숙해지십시오.

> "어떤 사람들은 일을 하는 데 큰 즐거움을 느끼고 다른 사람들은 그것으로부터 큰 보상을 원합니다. 그러나 현명한 사람은 일 그 자체에서 보상을 찾습니다."
> —세네카, 《도덕 서한》, 9.12 (의역)

> "성공은 비천한 사람과 재능이 없는 사람에게 오지만 위대한 사람의 특별한 특징은 인간 삶의 재앙과 공황을 이겨내는 것이다."
>
> -- 세네카, 《섭리에 대하여》, 4.1

> "준비되지 않은 자는 사소한 일에도 공황 상태에 빠진다."
>
> -세네카, 《도덕 서한》, 107.4

::: {.callout-note title="9월 24일: 일어날 수 있는 모든 일에 대해 생각해 보았는가?" icon="false"}
<br/>
<br/>
<br/>
:::

::: {.callout-note title="9월 25일: 나는 무엇의 노예인가?" icon="false"}
<br/>
<br/>
<br/>
:::

::: {.callout-note title="9월 26일: 어떤 한가한 여가를 더 만족스러운 것으로 대체할 수 있을까?" icon="false"}
<br/>
<br/>
<br/>
:::

::: {.callout-note title="9월 27일: 번영과 어려움이 각각 나에 대해 무엇을 드러내는가?" icon="false"}
<br/>
<br/>
<br/>
:::

::: {.callout-note title="9월 28일: 오늘 일어나는 일에 나는 어떻게 반응할 것인가?" icon="false"}
<br/>
<br/>
<br/>
:::

::: {.callout-note title="9월 29일: 내 눈이 내 배보다 큰 곳은 어디인가?" icon="false"}
<br/>
<br/>
<br/>
:::

::: {.callout-note title="9월 30일: 내 내면의 성채를 어떻게 강화할 수 있을까?" icon="false"}
<br/>
<br/>
<br/>
:::

# 40주차: 침묵을 연습하라

소셜 미디어는 우리에게 모든 것에 대해 의견을 갖도록 가르칩니다. 침묵은 우리에게 말하라고 손짓합니다. 우리는 시끄러운 문화에 살고 있으며 그에 맞춰 더 시끄러워지려고 노력합니다. 그것이 우리에게 얼마나 많은 문제를 일으킵니까? 우리가 매번 우리의 의견을 끼워 넣으려고 노력하는 것보다 다른 사람들의 말을 듣는 데 더 많은 시간을 보낸다면 얼마나 많은 것을 배울 수 있을까요? 우리가 말한 것 중 얼마나 많은 것을 후회하게 되었습니까? 진정으로 시끄러운 것은 아무 말도 하지 않는 것입니다. 이번 주에는 여기에 당신의 생각을 적어보되 그 중 얼마나 많은 것을 혼자 간직할 수 있는지 보십시오. 이번 주에 얼마나 입을 다무는지 당신의 침묵에 대담해지십시오.

> "혀로 넘어지는 것보다 발로 넘어지는 것이 낫다."
>
> -제논, 《저명한 철학자들의 생애》, 7.1.26에서 인용

> "말도 안 되는 소리를 하는 젊은이에게 제논은 '우리가 귀가 두 개이고 입이 하나뿐인 이유는 더 많이 듣고 덜 말하기 위함이다'라고 말했다."
>
> -디오게네스 라에르티우스. 《저명한 철학자들의 생애》, 7.1.23

> "카토는 대중을 움직일 수 있는 종류의 대중 연설을 연습했으며 적절한 정치 철학은 어떤 위대한 도시처럼 호전적인 요소를 유지하기 위해 주의를 기울여야 한다고 믿었습니다. 그러나 그는 다른 사람들 앞에서 연습하는 것을 본 적이 없으며 아무도 그가 연설을 연습하는 것을 들은 적이 없습니다. 사람들이 그의 침묵에 대해 그를 비난한다고 들었을 때 그는 '차라리 그들이 내 삶을 비난하지 않는 것이 낫다. 나는 내가 할 말이 차라리 하지 않는 것이 낫다는 것을 확신할 때만 말하기 시작한다'고 대답했습니다."
>
> -플루타르코스, 《소 카토》, 4

> "침묵은 삶의 많은 고통에서 배운 교훈이다."
>
> -- 세네카, 《티에스테스》, 309

::: {.callout-note title="10월 1일: 오늘 나는 어떻게 내 미덕을 빛나게 할 것인가?" icon="false"}
<br/>
<br/>
<br/>
:::

::: {.callout-note title="10월 2일: 지혜가 가장 귀중한 자산이라면 나는 그것에 어떻게 투자했는가?" icon="false"}
<br/>
<br/>
<br/>
:::

::: {.callout-note title="10월 3일: 나는 우리 모두가 하나 즉 같은 전체의 일부인 것처럼 사는가?" icon="false"}
<br/>
<br/>
<br/>
:::

::: {.callout-note title="10월 6일: 나 자신 외에 누구를 응원할 수 있을까?" icon="false"}
<br/>
<br/>
<br/>
:::

::: {.callout-note title="10월 7일: 왜 나의 잘못이 나를 가장 아프게 하는가?" icon="false"}
<br/>
<br/>
<br/>
:::

# 41주차: 사랑을 실천하라

우리 모두가 상호 이익과 친밀감으로 연결된 유기적 전체의 일부라는 스토아 학파의 공감(sympatheia) 개념은 황금률보다 더 위대합니다. 다른 사람을 당신이 대우받고 싶은 대로 대하지 마십시오. 당신 자신을 대하듯이 그들을 대하십시오. 왜냐하면 우리 모두는 하나이기 때문입니다. 세네카는 다른 인간을 만날 때마다 친절의 기회를 보았다고 말했습니다. 그는 헤카토로부터 사랑받고 싶다면 할 일은 단 하나 즉 다른 사람을 사랑하는 것이라는 것을 배웠습니다. 이번 주에 누구에게 사랑을 줄 수 있습니까? 어떤 친절을 베풀 수 있습니까? 낯선 사람 친구 가족에게 당신의 감정을 어떻게 보여줄 수 있습니까? 우리 모두가 같은 전체의 일부라고 믿는다는 것을 어떻게 보여줄 수 있습니까?

> "헤카토는 '나는 약 약초 또는 특별한 주문 없이 만든 사랑의 묘약을 가르쳐 줄 수 있습니다. 사랑받고 싶다면 사랑하십시오'라고 말합니다."
>
> -세네카, 《도덕 서한》, 9.6

> "혜택은 묻힌 보물처럼 보관해야 하며 필요할 때만 파내야 합니다... 자연은 우리에게 모든 사람에게 선을 행하라고 명합니다... 인간이 있는 곳이면 어디든 친절의 기회가 있습니다."
>
> -- 세네카, 《행복한 삶에 대하여》, 24.2-3

> "자연은 우리를 한 가족으로 만들었습니다. 왜냐하면 우리 모두는 같은 근원에서 나와 같은 목적을 향해 나아갔기 때문입니다. 자연은 우리에게 상호 사랑을 부여하고 우리를 친구로 결합시켰습니다."
>
> -세네카, 《도덕 서한》, 95.52

::: {.callout-note title="10월 8일: 지혜보다 더 즐거운 것은 무엇인가?" icon="false"}
<br/>
<br/>
<br/>
:::

::: {.callout-note title="10월 9일: 나는 내 기준을 세웠고 그것을 사용하고 있는가?" icon="false"}
<br/>
<br/>
<br/>
:::

::: {.callout-note title="10월 10일: 내 원칙은 인내와 저항에 대해 무엇을 말해주는가?" icon="false"}
<br/>
<br/>
<br/>
:::

::: {.callout-note title="10월 11일: 정직이 나의 기본 설정인가?" icon="false"}
<br/>
<br/>
<br/>
:::

::: {.callout-note title="10월 12일: 사랑을 구하는 대신 먼저 줄 수 있을까?" icon="false"}
<br/>
<br/>
<br/>
:::

::: {.callout-note title="10월 13일: 복수가 상황을 더 좋게 만든 적이 있는가?" icon="false"}
<br/>
<br/>
<br/>
:::

# 42주차: 정직을 유일한 정책으로 삼으세요

황제로서 마르쿠스 아우렐리우스는 인류의 최선을 보지 못했습니다. 궁정에는 험담 자신을 발전시킬 기회를 보았을 때 친구를 팔아넘기는 사람들 탐욕 그리고 속임수가 있었을 것입니다. 그러나 그는 특히 정직에 대한 가짜 시도를 좋아하지 않았습니다. 그의 요점은 만약 당신이 "여기서 솔직하게 말할게요"라고 말해야 한다면 당신은 정직이 규칙이 아니라 예외라고 아무렇지 않게 말하고 있는 것입니다. 그것이 얼마나 슬픈 일입니까? 이제 그 작은 진술들이 우리에 대해 무엇을 말하는지 생각하고 우리의 기본 정책이 정직과 솔직함인지 확인해야 할 때입니다.

> "사람들이 당신에게 솔직하게 말하겠다고 말할 때 얼마나 썩고 사기적인가. 무슨 짓을 하고 있는가, 친애하는 친구여? 그것은 당신의 발표가 필요하지 않아야 하며 당신의 이마에 쓰여 있는 것처럼 당신의 목소리의 울림에서 들리는 것처럼 당신의 눈에서 번쩍이는 것처럼 쉽게 보여야 합니다. 마치 사랑하는 사람이 연인의 시선에서 모든 것을 보는 것처럼 말입니다. 요컨대 솔직하고 선한 사람은 냄새나는 염소와 같아야 합니다. 당신은 그들이 당신과 함께 방에 있을 때를 압니다. 계산된 '당신에게 솔직하게 말하는 것'은 단검과 같습니다. 양과 친구가 되는 늑대보다 더 나쁜 것은 없습니다. 거짓 우정을 무슨 수를 써서라도 피하십시오. 만약 당신이 선하고 솔직하고 선의를 가지고 있다면 그것은 당신의 눈에 보여야 하며 눈에 띄지 않아서는 안 됩니다."
>
> -마르쿠스 아우렐리우스, 《명상록》, 11.15

> "친구들에게 애정을 보이고 그들의 발전을 축하하는 것은 자연에 부합하는 일입니다. 마치 우리 자신의 것인 것처럼 말입니다. 만약 우리가 이것을 하지 않는다면 우리의 인식을 행사함으로써만 강화되는 미덕은 더 이상 우리 안에 지속되지 않을 것입니다."
>
> -세네카, 《도덕 서한》, 109.15

::: {.callout-note title="10월 15일: 나는 사람들에게 의심의 이익을 줄 것인가?" icon="false"}
<br/>
<br/>
<br/>
:::

::: {.callout-note title="10월 16일: 나에게 많은 도움이 된 이 철학을 어떻게 나눌 수 있을까?" icon="false"}
<br/>
<br/>
<br/>
:::

::: {.callout-note title="10월 17일: 어디에서 다른 사람들에게 친절을 베풀 수 있을까?" icon="false"}
<br/>
<br/>
<br/>
:::

::: {.callout-note title="10월 20일: 내 원칙이 내 삶에 드러나는가?" icon="false"}
<br/>
<br/>
<br/>
:::

# 43주차: 헐뜯지 말고 세워주세요

괴롭힘과 우월감이 일반적인 환경보다 더 나쁜 작업 환경이 있을까요? 때로는 지도자들이 그것이 직무 설명의 일부라고 생각하는 것 같습니다. 즉 그들은 사람들을 규제하고 통제하기 위해 거기에 있다는 것입니다. 사실 사람들을 헐뜯는 것은 믿을 수 없을 정도로 비생산적입니다. 시애틀 시호크스의 코치인 피트 캐롤은 다음과 같은 질문을 던집니다. 선수들에게 자신감이 그렇게 중요하다면 코치가 왜 그것을 손상시키는 일을 하겠습니까? 마음만 먹으면 누구든 쓰러뜨릴 수 있는 힘을 가진 마르쿠스 아우렐리우스는 거의 그렇게 하지 않았습니다. 대신 그는 공동체 지향적이고 겸손하고 준비되고 다른 사람들에게 관대하게 대하는 것이 더 낫다고 스스로에게 상기시켰습니다. 우리는 협력(synergia)을 위해 만들어졌고 공동으로 보유한 작업(praxeis koinonikas apodidonai)을 수행하기 위해 만들어졌습니다. 앞으로 나아가면서 그것에 대해 생각해 봅시다. 우리는 다른 사람들의 자신감을 키우는 데 어떻게 도움을 줄 수 있을까요? 그렇게 함으로써 우리 자신의 자신감을 어떻게 찾을 수 있을까요?

> "다른 사람에게 도움을 주는 것은 당신 자신에게 도움을 주는 것과 같습니다."
> —마르쿠스 아우렐리우스, 《명상록》, 7.13 (의역)

> "아침에 일어나기 힘들 때마다 당신이 다른 사람들과 함께 일할 목적으로 자연에 의해 만들어졌다는 것을 스스로에게 상기시키십시오.... 그리고 우리의 자연적인 목적이 더 적합하고 더 만족스럽습니다."
>
> -마르쿠스 아우렐리우스, 《명상록》, 8.12

::: {.callout-note title="10월 22일: 나는 실제로 발전하고 있는가 아니면 단지 허영심을 쫓고 있는가?" icon="false"}
<br/>
<br/>
<br/>
:::

::: {.callout-note title="10월 23일: 나는 나의 최고의 자질을 보여주고 있는가?" icon="false"}
<br/>
<br/>
<br/>
:::

::: {.callout-note title="10월 24일: 내 안에서 어떤 선함을 찾을 수 있을까? 그것을 표면으로 끌어낼 수 있을까?" icon="false"}
<br/>
<br/>
<br/>
:::

::: {.callout-note title="10월 25일: 이생에서 나의 임무는 무엇인가?" icon="false"}
<br/>
<br/>
<br/>
:::

::: {.callout-note title="10월 26일: 내 목표는 자연스럽고 도덕적이며 이성적인가?" icon="false"}
<br/>
<br/>
<br/>
:::

::: {.callout-note title="10월 27일: 어떤 나쁜 행동이나 선택이 나를 괴롭혔는가?" icon="false"}
<br/>
<br/>
<br/>
:::

::: {.callout-note title="10월 28일: 나 자신보다 더 큰 무언가의 일부가 되기 위해 무엇을 할 수 있을까?" icon="false"}
<br/>
<br/>
<br/>
:::

# 44주차: 있는 그대로 받아들이기

라인홀트 니부어의 평온의 기도는 많은 사람들에게 만트라입니다. "신이시여, 제가 바꿀 수 없는 것을 받아들일 평온을 주시고 제가 바꿀 수 있는 것을 바꿀 용기를 주시고 그 차이를 알 지혜를 주소서." 스토아 학파는 단순히 있는 그대로를 "받아들이는" 것을 넘어 그것에 대해 감사하고 행복하기를 원했습니다. 에픽테토스는 우리가 원하는 것이 아니라 일어날 일을 바랄 때 순조로운 삶을 얻는다고 가르쳤고 마르쿠스는 우리에게 닥치는 모든 것을 감사함으로 맞이해야 한다고 덧붙였습니다. "이것이 달랐으면 좋겠지만 참을게"가 아니라 "이렇게 되어서 기쁘다. 이것이 최선이다." 이번 주에는 그것을 시도해 보십시오.

> "모든 일이 당신이 원하는 대로 일어나기를 바라지 말고 오히려 모든 일이 실제로 일어나는 대로 일어나기를 바라십시오. 그러면 당신의 삶은 순조롭게 흐를 것입니다."
>
> —에픽테토스, 《엔키리디온》, 8

> "침묵은 안전한 요새입니다."
> — 에픽테토스, 《선집》, 131A (의역)

> "모든 것에 감사하십시오. 당신이 가진 모든 것은 신들의 선물입니다."
> —마르쿠스 아우렐리우스, 《명상록》, 1.17 (의역)
::: {.callout-note title="10월 29일: 어떻게 하면 내 성격을 향상시킬 수 있을까?" icon="false"}
<br/>
<br/>
<br/>
:::

::: {.callout-note title="10월 30일: 나 자신을 위해 어떤 시간을 되찾을 수 있으며 그 시간을 어떻게 사용할 것인가?" icon="false"}
<br/>
<br/>
<br/>
:::

::: {.callout-note title="10월 31일: 오늘 어떤 좋은 일을 할 수 있을까?" icon="false"}
<br/>
<br/>
<br/>
:::

::: {.callout-note title="11월 1일: 오늘 일어나는 모든 일을 사랑할 수 있을까?" icon="false"}
<br/>
<br/>
<br/>
:::

::: {.callout-note title="11월 2일: 나는 내 선택을 하고 무슨 일이든 받아들일 수 있을까?" icon="false"}
<br/>
<br/>
<br/>
:::

::: {.callout-note title="11월 3일: 이것이 어떻게 내가 정확히 필요했던 것일 수 있을까?" icon="false"}
<br/>
<br/>
<br/>
:::

::: {.callout-note title="11월 4일: 변화가 정말 그렇게 나쁜가? 현상 유지가 정말 그렇게 좋은가?" icon="false"}
<br/>
<br/>
<br/>
:::

# 45주차: 당신이 가진 진정한 힘

덧없는 힘이 있고 진정한 힘이 있습니다. 덧없는 힘은 빼앗길 수 있지만 진정한 힘은 우리의 마음과 뼈 속에 있습니다. 전자는 부 명성 높은 지위 그리고 이 모든 것들이 우리에게 다른 사람들에 대해 주는 영향력의 경향이 있습니다. 스토아 학파는 이러한 종류의 힘이 각 사람이 소유한 진정한 힘 즉 사물의 진정한 가치에 따라 추론하고 판단하고 선택하는 우리 마음의 힘보다 열등하다고 생각했습니다. 당신은 두 종류의 힘을 모두 가질 수 있지만 첫 번째 종류의 힘을 스토아 학파가 중요하게 생각했던 종류의 힘에 종속시킬 때만 가능합니다.

> "이것이 바로 행복한 사람의 미덕과 순조로운 삶을 구성하는 바로 그 것입니다. 즉 삶의 모든 일이 개별적인 신성한 정신과 우주의 감독자의 의지 사이의 조화에 모든 면에서 맞춰질 때입니다."
>
> -크리시포스, 《저명한 철학자들의 생애》, 7.1.88에서 인용

> "당신의 명성 돈 또는 지위에 의존하지 말고 당신의 것인 힘 즉 당신이 통제하고 통제하지 않는 것들에 대한 당신의 판단에 의존하십시오. 왜냐하면 이것만이 우리를 자유롭고 속박되지 않게 만들고 우리를 깊은 곳에서 목덜미를 잡고 부자와 권력자와 눈을 마주치게 들어 올리기 때문입니다."
>
> -에픽테토스, 《담화록》, 3.26.34-35

> "마침내 당신 안에 육체적 열정을 일으키고 당신을 단순한 꼭두각시처럼 끌어당기는 것보다 더 강력하고 신성한 것이 있다는 것을 이해하십시오. 지금 내 마음을 차지하고 있는 생각은 무엇입니까? 그것은 두려움 의심 욕망 또는 그와 비슷한 것이 아닙니까?"
>
> -마르쿠스 아우렐리우스, 《명상록》, 12.19

::: {.callout-note title="11월 5일: 내 성격이 순조로운 삶을 만들어내고 있는가?" icon="false"}
<br/>
<br/>
<br/>
:::

::: {.callout-note title="11월 6일: 나는 운명과 행운의 무작위성에 대비하고 있는가?" icon="false"}
<br/>
<br/>
<br/>
:::

::: {.callout-note title="11월 7일: 당신은 자신을 다스리려고 하는가 아니면 다른 사람들을 다스리려고 하는가?" icon="false"}
<br/>
<br/>
<br/>
:::

::: {.callout-note title="11월 10일: 다른 모든 것이 사라질 때 무엇이 남을 것인가?" icon="false"}
<br/>
<br/>
<br/>
:::

::: {.callout-note title="11월 11일: 오늘 나는 어떤 잘못된 판단을 지울 수 있을까?" icon="false"}
<br/>
<br/>
<br/>
:::

# 46주차: 다른 사람을 판단하지 말고 자신을 판단하라

모든 것을 아는 체하는 것보다 덜 철학적인 것은 없습니다. 이것은 특히 자신의 지식을 사용하여 다른 사람의 실수를 꾸짖고 자신의 지식이나 통찰력의 우월성을 선포하는 사람들에게 해당됩니다. 스토아 학파는 이런 식으로 행동하는 것이 철학의 전체 목적 즉 자기 교정을 위한 도구 다른 사람을 깎아내리는 무기가 아닌 우리 자신의 영혼을 위한 약으로서의 목적을 놓치는 것이라고 가르쳤습니다. 세네카의 편지는 두 번이나 우리의 결점을 문지르거나 긁어내는 비유를 사용합니다. 우리는 우리 자신을 "철학의 원리의 보살핌 속에" 있는 것으로 보거나 나중에 에픽테토스가 철학자의 강의실을 언급할 때 말했듯이 우리 자신의 치료를 위한 병원으로 보아야 합니다. 이번 주에는 이 저널에 다른 사람에 대한 단 하나의 불평이나 문제도 적지 마십시오. 당신을 괴롭히는 것에 집중하십시오.

> "관대하게 주십시오. 당신이 가진 것을 다른 사람들과 나누는 데 주저하지 마십시오."
> —세네카, 《헤라클레스》, 1 (의역)

> "뛰어난 마음을 가진 어떤 사람들은 미덕을 빨리 파악하거나 자신 안에서 그것을 생산합니다. 그러나 다른 어둡고 게으른 유형들은 나쁜 습관에 방해를 받아 녹슨 영혼을 끊임없이 문질러 닦아야 합니다.... 약한 종류들은 우리가 그들을 철학의 원리의 보살핌에 맡기면 그들의 나쁜 의견으로부터 도움을 받고 들어 올려질 것입니다."
> —세네카, 《도덕 서한》, 95.36-37

> "여러분, 철학자의 강의실은 병원입니다. 여러분은 그곳에서 즐거움을 느끼며 걸어 나와서는 안 되며 고통을 느끼며 걸어 나와야 합니다. 왜냐하면 여러분은 들어갈 때 건강하지 않기 때문입니다."
> —에픽테토스, 《담화록》, 3.23.30

::: {.callout-note title="11월 12일: 오늘 책임은 나에게서 끝날 수 있을까?" icon="false"}
<br/>
<br/>
<br/>
:::

::: {.callout-note title="11월 13일: 불평이 무엇을 성취하는가?" icon="false"}
<br/>
<br/>
<br/>
:::

::: {.callout-note title="11월 14일: 나는 내 문제 위에 부정적인 생각을 더할 것인가?" icon="false"}
<br/>
<br/>
<br/>
:::

::: {.callout-note title="11월 15일: 오늘 나는 변화의 흐름을 받아들일 것인가?" icon="false"}
<br/>
<br/>
<br/>
:::

::: {.callout-note title="11월 16일: 나는 특정 결과에 대한 희망과 두려움을 모두 멈출 수 있을까?" icon="false"}
<br/>
<br/>
<br/>
:::

::: {.callout-note title="11월 17일: 다른 사람을 판단하는 것이 정말 내 자리인가?" icon="false"}
<br/>
<br/>
<br/>
:::

::: {.callout-note title="11월 18일: 나는 좋은 스토아적 생각을 실천하고 있는가?" icon="false"}
<br/>
<br/>
<br/>
:::

# 47주차: 놓아주기 연습

우리는 사랑하는 것을 잃을 때 고통받고 사랑하는 사람을 잃을 때 가장 고통받습니다. 이는 삶의 자연스럽고 피할 수 없는 부분입니다. 스토아 학파는 이 고통이 우리가 사랑의 대상을 소유하고 있다는 믿음 즉 우리가 말하듯이 "우리 자신의 일부"라는 믿음에 의해 증가한다고 말합니다. 이 믿음은 그들에 대한 우리의 사랑과 보살핌을 증가시키는 것이 아니라 오히려 우리가 일어날 일을 통제하지 못한다는 단순한 사실을 무시하는 집착의 한 형태입니다. 우리 자신의 몸은 물론이고 우리가 사랑하는 사람들에게 일어날 일도 마찬가지입니다. 에픽테토스는 사랑하는 자녀 가족 또는 친구에게 잘 자라고 인사할 때마다 이 사람들이 귀중한 깨지기 쉬운 유리와 같다는 것을 기억하고 잠자는 동안 상황이 얼마나 극적으로 변할 수 있는지 기억하는 강력한 수련을 가르쳤습니다. 마르쿠스 역시 밤에 아이들을 재우면서 자신의 가족과 함께 이것을 실천하기 위해 애썼습니다. 요점은 병적으로 되는 것이 아니라 감사와 일종의 겸손함을 만드는 것입니다. 이번 주에는 누구도 특히 사랑하는 사람을 당연하게 여기지 마십시오.

> "무언가를 잃는 고통을 경험할 때마다 그것을 당신 자신의 일부처럼 대하지 말고 깨지기 쉬운 유리처럼 대하십시오. 그래서 그것이 떨어질 때 당신은 그것을 기억하고 괴로워하지 않을 것입니다. 마찬가지로 당신의 자녀 형제 또는 친구에게 키스할 때마다 당신이 바랄 수 있는 모든 것을 경험 위에 덧씌우지 말고 그것들을 뒤로하고 멈추십시오. 마치 승리한 장군들 뒤에 타서 그들이 필멸자임을 상기시키는 사람들처럼 말입니다. 같은 방식으로 당신의 소중한 사람이 당신의 소유물 중 하나가 아니라 영원히가 아니라 지금 주어진 것이라는 것을 스스로에게 상기시키십시오."
> —에픽테토스, 《담화록》, 3.24.84-86A

> "그러나 현명한 사람은 아무것도 잃을 수 없습니다. 그러한 사람은 모든 것을 자신을 위해 저장해 두었고 행운에 아무것도 남기지 않았으며 자신의 재산은 미덕에 굳게 묶여 있으며 우연에서 아무것도 요구하지 않으므로 증가하거나 감소할 수 없습니다."
> —세네카, 《현자의 견고함에 대하여》, 5.4

::: {.callout-note title="11월 19일: 나는 상황을 받아들이고 여전히 선을 행하고 선하게 되기 위해 싸울 것인가?" icon="false"}
<br/>
<br/>
<br/>
:::

::: {.callout-note title="11월 20일: 매 순간 어디에서 영원함을 찾을 수 있을까?" icon="false"}
<br/>
<br/>
<br/>
:::

::: {.callout-note title="11월 21일: 지금 이 순간을 어떻게 충분하게 만들 수 있을까?" icon="false"}
<br/>
<br/>
<br/>
:::

::: {.callout-note title="11월 22일: 나는 무엇을 비합리적으로 잃을까 두려워하는가?" icon="false"}
<br/>
<br/>
<br/>
:::

::: {.callout-note title="11월 24일: 사랑하는 사람을 소유물이 아닌 선물로 어떻게 볼 수 있을까?" icon="false"}
<br/>
<br/>
<br/>
:::

::: {.callout-note title="11월 25일: 돈이 더 많아지면 정말 상황이 나아질까?" icon="false"}
<br/>
<br/>
<br/>
:::

# 48주차: 매일 삶의 장부를 맞추세요

우리는 삶의 경험 통찰력 좌절 예상치 못한 어려움과 승리 등을 모으는 방법으로 일기를 씁니다. 이 모든 것에서 우리는 삶의 길에서 우리의 진전을 계산하고 있습니다. 로마 곡물 창고의 장부를 관리하는 책임자였던 장인이었던 세네카는 매일 삶의 장부를 맞추는 비유를 좋아했습니다. 미루기보다는 매일 우리의 충동은 가능한 한 많은 것을 완성으로 이끄는 것이어야 합니다. 왜냐하면 우리는 내일이 무엇을 가져올지 결코 알지 못하기 때문입니다. 에픽테토스 역시 학생들에게 중요한 것은 그들이 시작했다는 것이라고 말하곤 했습니다. 즉 연습하고 배우고 더 나아지기 시작했다는 것입니다. 이번 주에는 당신이 걷고 있는 여정에 대해 자신에게 공을 돌리고 당신이 얼마나 멀리 왔는지(그리고 얼마나 멀리 가야 하는지) 성찰하십시오.

> "친절은 결코 헛되지 않습니다."
> —세네카, 《도덕 서한》, 81.19 (의역)

> "저를 믿으세요, 곡물 시장의 대차대조표보다 자신의 삶의 대차대조표를 작성하는 것이 더 낫습니다."
> —세네카, 《인생의 짧음에 대하여》, 18.3B

> "나는 당신의 스승이고 당신은 내 학교에서 배우고 있습니다. 내 목표는 당신을 완성으로 이끌고 방해받지 않고 강박적인 행동에서 자유롭고 제지받지 않고 부끄러움 없이 자유롭고 번영하고 행복하며 크고 작은 일에서 신을 바라보게 하는 것입니다. 당신의 목표는 이 모든 것을 배우고 부지런히 실천하는 것입니다. 그렇다면 당신이 올바른 목표를 가지고 있고 내가 올바른 목표와 올바른 준비를 모두 가지고 있다면 왜 일을 완성하지 않습니까? 무엇이 빠졌습니까? ... 그 일은 매우 실현 가능하며 우리 힘 안에 있는 유일한 것입니다.... 과거를 놓아주십시오. 우리는 단지 시작해야 합니다. 저를 믿으시면 보게 될 것입니다."
> —에픽테토스, 《담화록》, 2.19.29-34

::: {.callout-note title="11월 26일: 나는 어떤 사소한 비교로 나 자신을 괴롭히고 있는가?" icon="false"}
<br/>
<br/>
<br/>
:::

::: {.callout-note title="11월 27일: 어떤 불안의 원천을 차단할 수 있을까?" icon="false"}
<br/>
<br/>
<br/>
:::

::: {.callout-note title="11월 28일: 내가 말하지 않은 채로 나를 괴롭히는 것은 무엇인가?" icon="false"}
<br/>
<br/>
<br/>
:::

::: {.callout-note title="11월 29일: 어떻게 하면 덜 동요하고 그것에 대해 덜 불평할 수 있을까?" icon="false"}
<br/>
<br/>
<br/>
:::

::: {.callout-note title="11월 30일: 나는 우주의 인력을 받아들일 준비가 되었는가?" icon="false"}
<br/>
<br/>
<br/>
:::

::: {.callout-note title="12월 1일: 오늘을 마지막 날처럼 산다면 나는 무엇을 할 것인가?" icon="false"}
<br/>
<br/>
<br/>
:::

::: {.callout-note title="12월 2일: 어떻게 하면 내 행동을 의미 있게 만들 수 있을까?" icon="false"}
<br/>
<br/>
<br/>
:::

# 49주차: 시간에 인색하라

우리가 가장 흔히 듣는 말 중 하나는 "인생은 짧다"입니다. 그렇지만 세네카가 말했듯이 그것을 어떻게 사용하는지 안다면 충분히 길기도 합니다. 그것의 첫 번째 단계는? 다른 사람들에게 너무 많이 주지 않는 것입니다. 우리 시간에 대해 인색해지는 것은 강력한 수련이며 이 재생 불가능한 자원을 낭비하는 것을 막을 수 있습니다. 당신의 삶에서 좋은 목적 없이 많은 시간을 소비하는 것은 무엇입니까? 어떤 오락과 욕망이 우리에게 좋은 보답을 주지 않고 우리의 시간을 소비합니까? 그 목록을 검토하면서 그것에 대해 무언가를 하겠다는 약속을 하십시오. 결국 인생은 짧습니다. 당신은 너무 많이 여유가 없습니다.

> "역사의 모든 천재들이 이 단일 주제에 집중하더라도 그들은 인간 마음의 어둠에 대한 당혹감을 결코 완전히 표현할 수 없을 것입니다. 아무도 자신의 재산의 1인치도 포기하지 않을 것이며 이웃과의 사소한 분쟁은 지옥을 의미할 수 있습니다. 그러나 우리는 다른 사람들이 우리의 삶을 침해하도록 쉽게 허용합니다. 더 나쁜 것은 우리는 종종 그것을 차지할 사람들을 위해 길을 닦아줍니다. 아무도 자신의 돈을 지나가는 사람들에게 나눠주지 않지만 우리 각자는 얼마나 많은 사람들에게 우리의 삶을 나눠줍니까! 우리는 재산과 돈에 인색하지만 시간에 대해서는 너무 적게 생각합니다. 우리 모두가 가장 인색해야 할 유일한 것에 대해서 말입니다."
> — 세네카, 《인생의 짧음에 대하여》, 3.1-2

> "우리가 살 시간이 너무 짧다는 것은 전혀 사실이 아니며 우리가 그것의 상당 부분을 낭비한다는 것입니다. 인생은 충분히 길고 우리가 그것을 잘 쓴다면 많은 위대한 일을 할 수 있는 충분한 척도로 주어집니다. 그러나 그것이 사치와 태만의 배수구로 쏟아져 내리고 좋은 목적에 사용되지 않을 때 우리는 마침내 그것이 지나가는 것을 인식하기도 전에 지나갔다는 것을 보게 됩니다. 그리고 그래서 그렇습니다. 우리는 짧은 인생을 받지 않고 우리가 그렇게 만듭니다."
> — 세네카, 《인생의 짧음에 대하여》, 1.3-4A

::: {.callout-note title="12월 3일: 나는 이 철학으로 어떤 실제적인 문제를 해결하고 있는가?" icon="false"}
<br/>
<br/>
<br/>
:::

::: {.callout-note title="12월 4일: 나는 진정으로 무엇을 소유하고 있는가?" icon="false"}
<br/>
<br/>
<br/>
:::

::: {.callout-note title="12월 5일: 어떤 불쾌한 생각에 직면하고 그것을 내 장점으로 활용할 수 있을까?" icon="false"}
<br/>
<br/>
<br/>
:::

::: {.callout-note title="12월 6일: 아직 할 수 있을 때 지금 살기 위해 무엇을 할 수 있을까?" icon="false"}
<br/>
<br/>
<br/>
:::

::: {.callout-note title="12월 7일: 운명이 내게 준 패를 사랑할 수 있을까?" icon="false"}
<br/>
<br/>
<br/>
:::

::: {.callout-note title="12월 8일: 내가 직면해야 할 감정이 있는가?" icon="false"}
<br/>
<br/>
<br/>
:::

# 50주차: 리듬을 유지하라

마르쿠스 아우렐리우스는 황제로서 자신이 웅장하고 위대한 역사의 일부라는 것을 알았을 것입니다. 철학자로서 그는 또한 모든 사람이 역사와 자신의 삶을 통해 맥동하는 리듬의 일부라는 것을 알았고 그 박자를 잃지 않도록 스스로에게 상기시키는 것을 좋아했습니다. 철학으로 돌아가라, 그는 표류할 때 스스로에게 말했을 것입니다. 산만함에 굴복하지 마라. 사실 그는 끊임없이 그것으로 돌아가려고 노력했습니다. 그러한 종류의 인식(prosochē, 특별한 주의를 기울이는 것)은 그가 에픽테토스를 읽으면서 배운 것입니다. 에픽테토스는 그의 학생들에게 우리 중 누구도 완벽할 수는 없지만 우리가 미끄러지기 시작할 때 우리가 있어야 할 곳에서 표류할 때 우리 자신을 잡을 수 있다고 말했습니다. 이번 주에 그 리듬을 느낄 수 있습니까? 당신이 정말로 그것에 몰입했다고 느꼈을 때의 예를 들 수 있습니까?

> "과거의 긴 회랑 즉 수없이 이어지는 제국과 왕국의 회랑을 걸어보십시오. 그리고 미래도 볼 수 있습니다. 왜냐하면 그것은 분명히 똑같을 것이고 현재의 리듬에서 벗어날 수 없을 것이기 때문입니다. 우리가 40년을 경험했든 영겁을 경험했든 그것은 모두 하나입니다. 더 볼 것이 무엇이 있습니까?"
> —마르쿠스 아우렐리우스, 《명상록》, 7.49

> "상황에 의해 완전한 혼란에 빠진 것처럼 보일 때 빨리 정신을 차리십시오. 필요 이상으로 리듬에서 벗어나지 마십시오. 끊임없이 그것으로 돌아가면 박자를 유지할 수 있을 것입니다."
> —마르쿠스 아우렐리우스, 《명상록》, 6.11

> "주의력이 잠시 흐트러졌을 때 원할 때마다 다시 집중할 수 있을 것이라고 생각하지 마십시오. 대신 오늘의 실수 때문에 뒤따르는 모든 것이 필연적으로 더 나빠질 것이라는 것을 명심하십시오.... 실수로부터 자유로워지는 것이 가능합니까? 결코 그렇지 않습니다. 그러나 항상 실수를 피하기 위해 노력하는 사람이 되는 것은 가능합니다. 왜냐하면 우리는 결코 주의력을 흐트러뜨리지 않음으로써 적어도 몇 가지 실수를 피하는 것에 만족해야 하기 때문입니다."
> —에픽테토스, 《담화록》, 4.12.1; 19

::: {.callout-note title="12월 10일: 그렇게 자유롭게 쓰는 시간에 대한 대가로 무엇을 얻고 있는가?" icon="false"}
<br/>
<br/>
<br/>
:::

::: {.callout-note title="12월 11일: 당신은 위엄과 용기를 가지고 살고 있는가?" icon="false"}
<br/>
<br/>
<br/>
:::

::: {.callout-note title="12월 12일: 어떤 방해가 있더라도 삶의 리듬을 유지할 것인가?" icon="false"}
<br/>
<br/>
<br/>
:::

::: {.callout-note title="12월 13일: 내가 받은 시간에 감사할 수 있을까?" icon="false"}
<br/>
<br/>
<br/>
:::

::: {.callout-note title="12월 14일: 내 삶은 무엇의 증거가 될 것인가?" icon="false"}
<br/>
<br/>
<br/>
:::

::: {.callout-note title="12월 15일: 오늘 나는 조금 더 나아질 것인가?" icon="false"}
<br/>
<br/>
<br/>
:::

::: {.callout-note title="12월 16일: 나는 자신감을 키우기 위해 무엇을 하고 있는가?" icon="false"}
<br/>
<br/>
<br/>
:::

# 51주차: 당신의 주장을 펼치세요

우리는 위대한 작가나 우리가 존경하는 지도자들의 말을 수집하는 것을 좋아합니다. 그것들은 종종 삶의 길에서 우리에게 만트라가 되어 지침과 확신을 제공합니다. 그러나 세네카가 상기시키듯이 진실은 독점되지 않았습니다. 우리는 매주 우리 자신의 지혜를 공식화하고 우리의 연구 실천 훈련에 기초하여 우리 자신의 주장을 펼치는 데 시간과 노력을 들여야 합니다. 그것이 이 저널의 목적입니다. 스토아 학파의 지혜를 성찰하고 우리 자신의 지혜를 더하는 것입니다. 세네카는 우리에게 우리 자신의 길을 개척하고 책임을 지고 우리 자신의 주장을 펼치라고 촉구했습니다. 자, 해봅시다. 이 페이지들이 당신이 자신의 경험으로 배운 통찰력을 반영하게 하십시오. 당신이 스토아 학파로부터 받은 영감이 당신 자신의 수련 알림 관점을 창조하게 하십시오.

> "매일 저녁 당신의 행동을 검토하십시오. 무엇을 잘했는지 무엇을 잘못했는지 스스로에게 물어보십시오."
> —세네카, 《도덕 서한》, 28 (의역)

> "선조들의 발자취를 따라 걷지 않겠습니까? 나는 분명히 오래된 길을 이용할 것이지만 더 짧고 부드러운 길을 찾는다면 그곳에 길을 낼 것입니다. 이 길을 개척한 사람들은 우리의 주인이 아니라 우리의 안내자입니다. 진실은 모든 사람에게 열려 있으며 독점되지 않았습니다."
> —세네카, 《도덕 서한》, 33.11

> "다른 사람에게 선을 행할 때 당신이 보상을 받아야 하는 것처럼 행동하지 마십시오. 당신은 단지 당신의 본성에 따라 행동했을 뿐입니다."
> —마르쿠스 아우렐리우스, 《명상록》, 5.6 (의역)
::: {.callout-note title="12월 17일: 나는 나 자신을 얼마나 잘 아는가?" icon="false"}
<br/>
<br/>
<br/>
:::

::: {.callout-note title="12월 18일: 우리 모두의 끝은 소중하지만 내 목적은?" icon="false"}
<br/>
<br/>
<br/>
:::

::: {.callout-note title="12월 19일: 나보다 훨씬 더 큰 것에 집중할 수 있는 것은 무엇인가?" icon="false"}
<br/>
<br/>
<br/>
:::

::: {.callout-note title="12월 20일: 나는 정말 무엇을 그렇게 두려워하는가?" icon="false"}
<br/>
<br/>
<br/>
:::

::: {.callout-note title="12월 21일: 오늘을 최대한 활용하고 그렇게 함으로써 내 인생을 최대한 활용하는 방법은 무엇일까?" icon="false"}
<br/>
<br/>
<br/>
:::

::: {.callout-note title="12월 22일: 오늘 나는 어떤 지혜를 창조할 것인가?" icon="false"}
<br/>
<br/>
<br/>
:::

# 52주차: 말을 행동으로 옮기세요

마르쿠스는 그의 일기에 많은 시간을 보냈지만 그 페이지 안에서 우리는 그가 그것들을 버리고 그 페이지를 절대 읽지 말라고 스스로를 훈계하는 것을 발견합니다. 왜냐하면 그는 그것들이 당면한 본질적인 과제로부터의 변명이 되기를 원하지 않았기 때문입니다. 삶의 기술은 좋은 사람이 되려는 우리 자신의 노력 외에는 어디에서도 찾을 수 없을 것입니다. 그것이 이 저널의 목표라는 것을 결코 잊지 마십시오. 그것은 예쁜 생각으로 페이지를 채우는 것이 아니라 당신이 행동을 취하도록 영감을 주고 세네카가 말했듯이 말을 행동으로 바꾸도록 하는 것입니다. 그 안에서 우리는 올해를 끝낼 완벽한 장소를 가지고 있습니다. 궁극적인 스토아적 프롬프트와 함께 말입니다. 당신 자신의 구조에 적극적으로 참여하십시오.

> "방황하는 것을 멈추십시오! 당신은 자신의 공책이나 고대 역사 또는 노년에 즐기기 위해 수집한 선집을 읽을 것 같지 않습니다. 삶의 목적에 바쁘게 지내고 공허한 희망을 버리고 자신을 구하는 데 적극적으로 참여하십시오. 만약 당신이 자신을 조금이라도 아낀다면 그리고 할 수 있을 때 하십시오."
> —마르쿠스 아우렐리우스, 《명상록》, 3.14
> "미루는 것은 인생을 낭비하는 가장 큰 원인입니다. 지금 이 순간을 사십시오."
> —마르쿠스 아우렐리우스, 《명상록》, 2.14 (의역)

> "마치 우리가 삶의 마지막에 온 것처럼 마음을 준비합시다. 아무것도 미루지 맙시다. 매일 삶의 장부를 맞춥시다. 삶의 가장 큰 결점은 항상 불완전하고 그 일부가 미뤄진다는 것입니다. 매일 자신의 삶에 마침표를 찍는 사람은 결코 시간이 부족하지 않습니다."
> —세네카, 《도덕 서한》, 101.7B-8A

::: {.callout-note title="12월 26일: 나는 어디에서 인생을 낭비하고 있는가?" icon="false"}
<br/>
<br/>
<br/>
:::

::: {.callout-note title="12월 27일: 내 영혼이 내 몸보다 강한가?" icon="false"}
<br/>
<br/>
<br/>
:::

::: {.callout-note title="12월 28일: 백 년 후에 누가 기억하거나 기억될 것인가?" icon="false"}
<br/>
<br/>
<br/>
:::

::: {.callout-note title="12월 29일: 나는 무엇에 감사하는가?" icon="false"}
<br/>
<br/>
<br/>
:::

::: {.callout-note title="12월 31일: 이 말들을 어떻게 행동으로 옮길 것인가?" icon="false"}
<br/>
<br/>
<br/>
:::

# 더 많은 스토아적 프롬프트

이 저널은 《데일리 스토익》의 궁극적인 동반자로 설계되었고 《데일리 스토익》은 독자가 원하는 만큼 여러 번 읽도록 설계되었지만 특히 이 저널을 두 번째로 접하는 경우 더 많은 프롬프트와 스토아적 읽을거리를 찾고 있을 수 있습니다. 그것은 우리가 기꺼이 제공하는 것입니다.

먼저, 우리는 DailyStoic.com에서 매일 스토아적 지혜의 무료 이메일을 보냅니다. 아직 가입하지 않았다면 꼭 해야 합니다!

둘째, 함께 일기를 쓸 고전 및 현대 스토아 텍스트를 찾고 있다면 몇 가지 권장 사항이 있습니다.

* 마르쿠스 아우렐리우스의 《명상록》(모던 라이브러리의 그레고리 헤이스 번역을 강력히 추천합니다)
* 세네카의 《도덕 서한》(펭귄 클래식 요약본은 훌륭하며 팀 페리스가 출간한 전체 무료 전자책 버전도 있습니다)
* 에픽테토스의 《담화록 및 선집》(다시 말하지만, 펭귄 클래식보다 더 나은 것은 어렵습니다)
* 피에르 아도의 《내면의 성채: 마르쿠스 아우렐리우스의 명상록》(이것은 마르쿠스 아우렐리우스의 철학과 그를 움직이게 하는 것에 대한 훌륭한 심층 분석입니다)
* 푸블릴리우스 시루스의 《푸블릴리우스 시루스의 도덕적 격언: 로마 노예》(또 다른 노예 출신 철학자로, 그의 간결한 경구는 매일 쓸 거리를 줄 것입니다)

스토아적 수련과 실천 그리고 그 목적에 대해 더 배우고 싶다면 다음 자료를 추천합니다.

* 피에르 아도의 《삶의 방식으로서의 철학: 소크라테스에서 푸코까지의 영적 수련》 3장 (Wiley-Blackwell, 1995)
* 리처드 소랍지의 《감정과 마음의 평화: 스토아적 동요에서 기독교적 유혹까지》 15-16장 (Oxford University Press, 2000)
* 도널드 로버트슨의 《인지 행동 치료의 철학: 이성적이고 인지적인 심리 치료로서의 스토아 철학》 2부 (Karnac Books, 2010) 또는 그의 똑같이 훌륭한 《스토아 철학과 행복의 기술》 (Hodder & Stoughton, 2013)
* 마시모 피글리우치의 《스토아 학파가 되는 법: 고대 철학을 사용하여 현대 생활을 사는 법》 3부 (Basic Books, 2017)

위의 제목 외에 광범위한 스토아 독서를 위해 우리는 다음 목록을 편집했으며 이 목록은 www.dailystoic.com/books-on-stoicism에서 지속적으로 수정되고 추가되고 있습니다.

* 제임스 B. 스톡데일의 《불 속의 용기: 인간 행동 실험실에서 에픽테토스의 교리 시험하기》 (Hoover Institution Press, 1993)
* 제임스 롬의 《매일 죽기: 네로 궁정의 세네카》 (Vintage, 2014)
* 롭 굿맨과 지미 소니의 《로마의 마지막 시민: 카토의 삶과 유산, 카이사르의 필생의 적》 (St. Martin's Griffin, 2014)
* 톰 울프의 《충만한 인간》 (Dial Press, 2001)
* 윌리엄 B. 어바인의 《좋은 삶으로의 안내: 스토아적 기쁨의 고대 예술》 (Oxford University Press, 2008)
* 알랭 드 보통의 《철학의 위안》 (Vintage, 2001)
* 나심 니콜라스 탈레브의 《안티프래질: 무질서에서 이익을 얻는 것들》 (Random House, 2014)
* 제임스 밀러의 《검토된 삶: 소크라테스에서 니체까지》 (Picador, 2012)
* 낸시 셔먼의 《스토아 전사들: 군사 정신 뒤에 숨겨진 고대 철학》 (Oxford University Press, 2007)
* 존 셀러스의 《스토아 철학》 (University of California Press, 2006)
* R. W. 샤플스의 《스토아 학파, 에피쿠로스 학파, 회의론자: 헬레니즘 철학 입문》 (Routledge, 1996)
* M. 앤드류 홀로왁의 《스토아 학파: 당혹스러운 사람들을 위한 안내서》 (Bloomsbury Academic, 2008)
* F. H. 샌드바흐의 《스토아 학파》 (Hackett Publishing Company, Inc., 1994)
* 마가렛 그레이버의 《스토아 철학과 감정》 (University of Chicago Press, 2009)
* 브래드 인우드의 《케임브리지 스토아 학파 동반자》 (Cambridge University Press, 2003)
* 로널드 파이스의 《모든 것에는 두 개의 손잡이가 있다: 삶의 기술에 대한 스토아 학파의 안내서》 (Hamilton Books, 2008)
* 줄스 에반스의 《삶과 다른 위험한 상황을 위한 철학》 (New World Library, 2013)
* 로렌스 C. 베커의 《새로운 스토아 철학: 개정판》 (Princeton University Press, 2017)
* 에밀리 윌슨의 《가장 위대한 제국: 세네카의 삶》 (Oxford University Press, 2014)